In [5]:
%reload_ext autoreload
%autoreload 2

import importlib
import itertools
import time
import io
import contextlib
from pathlib import Path

import numpy as np
import pandas as pd

import sim_instance_v3
importlib.reload(sim_instance_v3)

from model_modules.contract_v1 import ModuleSpec


# =============================================================================
# Overnight coarse sweep: smell-momentum oracle
# =============================================================================

OUT_DIR = Path("sweep_outputs")
OUT_DIR.mkdir(exist_ok=True)

RAW_PATH = OUT_DIR / "oracle_smell_decay_fill_coarse_50seed_raw.csv"
SUMMARY_PATH = OUT_DIR / "oracle_smell_decay_fill_coarse_50seed_summary.csv"


# -----------------------------------------------------------------------------
# Fixed run setup
# -----------------------------------------------------------------------------
SIM_LEN = 20_000
EVAL_LEN = 5_000

SEEDS = list(range(50))

env_kwargs = dict(
    radius=20,
    band=(9, 11),
    start_coord=(0, 0),
)

module_spec = ModuleSpec(
    orchestrator="oracle",
    pathfinder="oracle",
    eat="oracle",
    drink="oracle",
    explorer="smell_momentum",
)


# -----------------------------------------------------------------------------
# Coarse grid
# -----------------------------------------------------------------------------
DECAY_MULTS = [0.70, 0.80, 0.90]

# Broad around the previous best 1.60.
FILL_TARGETS = [1.30, 1.60, 1.90]

# Around previous useful momentum zone.
PERSIST_PS = [0.55, 0.75]

# Smell radius brackets current 12.
SMELL_RADII = [10, 14]

# Fixed smell explorer params.
TREND_EPS = 0.01
FOLLOW_P = 0.95
REVERSE_ON_DROP_P = 0.75
AVOID_REVERSE = True


configs = list(itertools.product(
    DECAY_MULTS,
    FILL_TARGETS,
    PERSIST_PS,
    SMELL_RADII,
))

print(f"configs: {len(configs)}")
print(f"seeds per config: {len(SEEDS)}")
print(f"total runs: {len(configs) * len(SEEDS)}")


# -----------------------------------------------------------------------------
# Resume support
# -----------------------------------------------------------------------------
if RAW_PATH.exists():
    df_existing = pd.read_csv(RAW_PATH)
    done_keys = set(
        zip(
            df_existing["seed"].astype(int),
            df_existing["decay_mult"].round(4),
            df_existing["fill_target"].round(4),
            df_existing["persist_p"].round(4),
            df_existing["smell_radius"].astype(int),
        )
    )
    rows = df_existing.to_dict("records")
    print(f"resuming: found {len(done_keys)} completed rows")
else:
    done_keys = set()
    rows = []


def make_oracle_params(fill_target, persist_p):
    oracle_params = sim_instance_v3.default_oracle_params()

    oracle_params["orchestrator"] = {
        "h_fill": fill_target,
        "s_fill": fill_target,
    }

    oracle_params["drink"] = {
        "fill_target": fill_target,
    }

    oracle_params["eat"] = {
        "fill_target": fill_target,
    }

    oracle_params["explorer"] = {
        "persist_p": persist_p,
        "avoid_reverse": AVOID_REVERSE,
        "trend_eps": TREND_EPS,
        "follow_p": FOLLOW_P,
        "reverse_on_drop_p": REVERSE_ON_DROP_P,
    }

    return oracle_params


def summarise_and_save(rows):
    df = pd.DataFrame(rows)
    df.to_csv(RAW_PATH, index=False)

    ok = df[df["error"].isna()].copy()

    summary = (
        ok.groupby(["decay_mult", "fill_target", "persist_p", "smell_radius"])
        .agg(
            mean_comfort_mean=("mean_comfort", "mean"),
            mean_comfort_std=("mean_comfort", "std"),

            eval_deaths_mean=("eval_deaths", "mean"),
            eval_deaths_median=("eval_deaths", "median"),
            eval_deaths_max=("eval_deaths", "max"),
            zero_death_seeds=("eval_deaths", lambda x: int((x == 0).sum())),

            eval_segments_mean=("eval_segments", "mean"),
            eval_segments_max=("eval_segments", "max"),
            eval_timeouts_mean=("eval_timeouts", "mean"),

            water_ticks_mean=("eval_water_ticks", "mean"),
            food_ticks_mean=("eval_food_ticks", "mean"),

            explorer_calls_mean=("explorer_calls", "mean"),
            smell_follow_mean=("smell_follow", "mean"),
            smell_reverse_mean=("smell_reverse", "mean"),
            momentum_persist_mean=("momentum_persist", "mean"),

            n=("seed", "count"),
        )
        .reset_index()
    )

    # Primary goal: deaths low.
    # Tie-breakers:
    #   - lower max deaths
    #   - more zero-death seeds
    #   - higher decay_mult preferred because it is the harder physics
    #   - higher comfort
    summary = summary.sort_values(
        [
            "eval_deaths_mean",
            "eval_deaths_max",
            "zero_death_seeds",
            "decay_mult",
            "mean_comfort_mean",
        ],
        ascending=[True, True, False, False, False],
    )

    summary.to_csv(SUMMARY_PATH, index=False)
    return df, summary


# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------
t0 = time.time()
run_i = len(done_keys)
total_runs = len(configs) * len(SEEDS)

for decay_mult, fill_target, persist_p, smell_radius in configs:
    for seed in SEEDS:
        key = (
            int(seed),
            round(float(decay_mult), 4),
            round(float(fill_target), 4),
            round(float(persist_p), 4),
            int(smell_radius),
        )

        if key in done_keys:
            continue

        run_i += 1

        oracle_params = make_oracle_params(
            fill_target=fill_target,
            persist_p=persist_p,
        )

        row = {
            "seed": seed,
            "decay_mult": decay_mult,
            "fill_target": fill_target,
            "persist_p": persist_p,
            "smell_radius": smell_radius,
            "avoid_reverse": AVOID_REVERSE,
            "trend_eps": TREND_EPS,
            "follow_p": FOLLOW_P,
            "reverse_on_drop_p": REVERSE_ON_DROP_P,
            "error": None,
        }

        try:
            # suppress per-run prints from sim_instance
            with contextlib.redirect_stdout(io.StringIO()):
                out = sim_instance_v3.sim_instance(
                    seed=seed,
                    sim_len=SIM_LEN,
                    eval_len=EVAL_LEN,

                    env_kwargs=env_kwargs,

                    module_spec=module_spec,
                    oracle_params=oracle_params,

                    curriculum_mode="band",
                    c_min=2,
                    c_max=9,
                    band_width=2,
                    curriculum_ramp_frac=0.6,
                    curriculum_sampling="uniform",
                    terminals_per_map=1,
                    life_cap=1000,

                    smell_radius=smell_radius,
                    decay_mult=decay_mult,

                    log_every=999_999,
                )

            stats = out.get("explorer_stats", {})

            row.update({
                "mean_comfort": out["mean_comfort"],
                "min_comfort": out["min_comfort"],
                "std_comfort": out["std_comfort"],

                "eval_deaths": out["death_count_eval"],
                "eval_death_rate": out["death_rate_eval"],
                "eval_timeouts": out["n_timeouts_eval"],
                "eval_segments": len(out["eval_segments"]),

                "eval_water_ticks": out["ticks_at_water_eval"],
                "eval_food_ticks": out["ticks_at_food_eval"],

                "train_wf": out["train_wf_trips"],
                "train_fw": out["train_fw_trips"],

                "explorer_type": out.get("explorer_type"),
                "explorer_calls": stats.get("n_calls"),
                "smell_follow": stats.get("n_smell_follow"),
                "smell_reverse": stats.get("n_smell_reverse"),
                "momentum_persist": stats.get("n_persist"),
                "random_turns": stats.get("n_random_turns"),
            })

            print(
                f"[{run_i:04d}/{total_runs}] "
                f"seed={seed:02d} decay={decay_mult:.2f} fill={fill_target:.2f} "
                f"p={persist_p:.2f} smellR={smell_radius:02d} | "
                f"comfort={row['mean_comfort']:.3f} deaths={row['eval_deaths']} "
                f"segments={row['eval_segments']}"
            )

        except Exception as e:
            row["error"] = repr(e)

            print(
                f"[{run_i:04d}/{total_runs}] FAILED "
                f"seed={seed:02d} decay={decay_mult:.2f} fill={fill_target:.2f} "
                f"p={persist_p:.2f} smellR={smell_radius:02d} | {repr(e)}"
            )

        rows.append(row)
        done_keys.add(key)

        # checkpoint every run
        if run_i % 1 == 0:
            df_tmp, summary_tmp = summarise_and_save(rows)

        # quick leaderboard every 25 runs
        if run_i % 25 == 0:
            elapsed = time.time() - t0
            print(f"\n--- checkpoint after {run_i} runs | elapsed {elapsed/60:.1f} min ---")
            display(summary_tmp.head(10))


df_raw, summary = summarise_and_save(rows)

print("\nDONE")
print("raw saved to:", RAW_PATH)
print("summary saved to:", SUMMARY_PATH)

display(summary.head(30))

configs: 36
seeds per config: 50
total runs: 1800
[0001/1800] seed=00 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.889 deaths=1 segments=6
[0002/1800] seed=01 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.896 deaths=0 segments=5
[0003/1800] seed=02 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.897 deaths=3 segments=8
[0004/1800] seed=03 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.924 deaths=0 segments=5
[0005/1800] seed=04 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.920 deaths=0 segments=5
[0006/1800] seed=05 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.928 deaths=2 segments=7
[0007/1800] seed=06 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.896 deaths=1 segments=6
[0008/1800] seed=07 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=0 segments=5
[0009/1800] seed=08 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.894 deaths=2 segments=7
[0010/1800] seed=09 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.856 deaths=1 segments=6
[0011/1800] seed=10 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.872 deaths=0 segments=5
[0012/1800] seed=11 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.902 deaths=1 segments=6
[0013/1800] seed=12 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.922 deaths=3 segments=8
[0014/1800] seed=13 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.879 deaths=2 segments=7
[0015/1800] seed=14 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=0 segments=5
[0016/1800] seed=15 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.906 deaths=0 segments=5
[0017/1800] seed=16 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.927 deaths=1 segments=6
[0018/1800] seed=17 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.852 deaths=1 segments=6
[0019/1800] seed=18 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.943 deaths=0 segments=5
[0020/1800] seed=19 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.899 deaths=5 segments=10
[0021/1800] seed=20 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.915 deaths=2 segments=7
[0022/1800] seed=21 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.898 deaths=1 segments=6
[0023/1800] seed=22 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.948 deaths=0 segments=5
[0024/1800] seed=23 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.911 deaths=1 segments=6
[0025/1800] seed=24 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.927 deaths=3 segments=8

--- checkpoint after 25 runs | elapsed 0.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.90342,0.024044,1.2,1.0,5,9,6.2,10,4.0,1136.72,449.08,729.72,196.0,50.6,119.32,25

[0026/1800] seed=25 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.867 deaths=0 segments=5
[0027/1800] seed=26 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=2 segments=7
[0028/1800] seed=27 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.892 deaths=2 segments=7
[0029/1800] seed=28 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.853 deaths=4 segments=9
[0030/1800] seed=29 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.941 deaths=0 segments=5
[0031/1800] seed=30 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.884 deaths=2 segments=7
[0032/1800] seed=31 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.902 deaths=1 segments=6
[0033/1800] seed=32 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.884 deaths=5 segments=10
[0034/1800] seed=33 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.910 deaths=2 segments=7
[0035/1800] seed=34 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.912 deaths=1 segments=6
[0036/1800] seed=35 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.853 deaths=2 segments=7
[0037/1800] seed=36 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.911 deaths=1 segments=6
[0038/1800] seed=37 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.893 deaths=0 segments=5
[0039/1800] seed=38 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.882 deaths=2 segments=7
[0040/1800] seed=39 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.890 deaths=3 segments=8
[0041/1800] seed=40 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.906 deaths=2 segments=7
[0042/1800] seed=41 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.895 deaths=1 segments=6
[0043/1800] seed=42 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.877 deaths=3 segments=8
[0044/1800] seed=43 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.875 deaths=2 segments=7
[0045/1800] seed=44 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.869 deaths=4 segments=9
[0046/1800] seed=45 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.863 deaths=2 segments=7
[0047/1800] seed=46 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.840 deaths=3 segments=8
[0048/1800] seed=47 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=2 segments=7
[0049/1800] seed=48 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.919 deaths=1 segments=6
[0050/1800] seed=49 decay=0.70 fill=1.30 p=0.55 smellR=10 | comfort=0.879 deaths=0 segments=5

--- checkpoint after 50 runs | elapsed 1.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.89533,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50

[0051/1800] seed=00 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.889 deaths=1 segments=6
[0052/1800] seed=01 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.896 deaths=0 segments=5
[0053/1800] seed=02 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.897 deaths=3 segments=8
[0054/1800] seed=03 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.907 deaths=2 segments=7
[0055/1800] seed=04 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.914 deaths=0 segments=5
[0056/1800] seed=05 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.928 deaths=2 segments=7
[0057/1800] seed=06 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.897 deaths=1 segments=6
[0058/1800] seed=07 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.891 deaths=0 segments=5
[0059/1800] seed=08 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.894 deaths=2 segments=7
[0060/1800] seed=09 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.856 deaths=1 segments=6
[0061/1800] seed=10 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.872 deaths=0 segments=5
[0062/1800] seed=11 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.902 deaths=1 segments=6
[0063/1800] seed=12 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.885 deaths=2 segments=7
[0064/1800] seed=13 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.874 deaths=2 segments=7
[0065/1800] seed=14 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.891 deaths=0 segments=5
[0066/1800] seed=15 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.863 deaths=2 segments=7
[0067/1800] seed=16 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.927 deaths=1 segments=6
[0068/1800] seed=17 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.852 deaths=1 segments=6
[0069/1800] seed=18 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.943 deaths=0 segments=5
[0070/1800] seed=19 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.913 deaths=1 segments=6
[0071/1800] seed=20 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.923 deaths=1 segments=6
[0072/1800] seed=21 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.854 deaths=0 segments=5
[0073/1800] seed=22 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.948 deaths=0 segments=5
[0074/1800] seed=23 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.894 deaths=1 segments=6
[0075/1800] seed=24 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.830 deaths=5 segments=10

--- checkpoint after 75 runs | elapsed 2.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
1,0.7,1.3,0.55,14,0.893652,0.029187,1.16,1.0,5,8,6.16,10,4.0,1103.64,443.32,714.84,199.28,51.72,114.24,25
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50

[0076/1800] seed=25 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.872 deaths=0 segments=5
[0077/1800] seed=26 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.924 deaths=0 segments=5
[0078/1800] seed=27 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.882 deaths=2 segments=7
[0079/1800] seed=28 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.857 deaths=2 segments=7
[0080/1800] seed=29 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.941 deaths=0 segments=5
[0081/1800] seed=30 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.884 deaths=2 segments=7
[0082/1800] seed=31 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.849 deaths=4 segments=9
[0083/1800] seed=32 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.882 deaths=2 segments=7
[0084/1800] seed=33 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.910 deaths=2 segments=7
[0085/1800] seed=34 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.846 deaths=6 segments=11
[0086/1800] seed=35 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.855 deaths=1 segments=6
[0087/1800] seed=36 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.869 deaths=2 segments=7
[0088/1800] seed=37 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=0 segments=5
[0089/1800] seed=38 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.882 deaths=2 segments=7
[0090/1800] seed=39 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=0 segments=5
[0091/1800] seed=40 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.906 deaths=2 segments=7
[0092/1800] seed=41 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.870 deaths=6 segments=11
[0093/1800] seed=42 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.877 deaths=3 segments=8
[0094/1800] seed=43 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.881 deaths=2 segments=7
[0095/1800] seed=44 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.900 deaths=2 segments=7
[0096/1800] seed=45 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.863 deaths=2 segments=7
[0097/1800] seed=46 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.840 deaths=3 segments=8
[0098/1800] seed=47 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.895 deaths=3 segments=8
[0099/1800] seed=48 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.895 deaths=1 segments=6
[0100/1800] seed=49 decay=0.70 fill=1.30 p=0.55 smellR=14 | comfort=0.879 deaths=0 segments=5

--- checkpoint after 100 runs | elapsed 3.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50

[0101/1800] seed=00 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.878 deaths=2 segments=7
[0102/1800] seed=01 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.885 deaths=0 segments=5
[0103/1800] seed=02 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.876 deaths=3 segments=8
[0104/1800] seed=03 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.855 deaths=3 segments=8
[0105/1800] seed=04 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.928 deaths=0 segments=5
[0106/1800] seed=05 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.886 deaths=3 segments=8
[0107/1800] seed=06 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.885 deaths=0 segments=5
[0108/1800] seed=07 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.893 deaths=0 segments=5
[0109/1800] seed=08 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.934 deaths=1 segments=6
[0110/1800] seed=09 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.873 deaths=3 segments=8
[0111/1800] seed=10 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.864 deaths=3 segments=8
[0112/1800] seed=11 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.874 deaths=2 segments=7
[0113/1800] seed=12 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.916 deaths=3 segments=8
[0114/1800] seed=13 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.927 deaths=3 segments=8
[0115/1800] seed=14 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.895 deaths=2 segments=7
[0116/1800] seed=15 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.870 deaths=6 segments=11
[0117/1800] seed=16 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.871 deaths=2 segments=7
[0118/1800] seed=17 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.911 deaths=1 segments=6
[0119/1800] seed=18 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.905 deaths=3 segments=8
[0120/1800] seed=19 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.861 deaths=0 segments=5
[0121/1800] seed=20 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.880 deaths=4 segments=9
[0122/1800] seed=21 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=3 segments=8
[0123/1800] seed=22 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.878 deaths=0 segments=5
[0124/1800] seed=23 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.912 deaths=5 segments=10
[0125/1800] seed=24 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.886 deaths=6 segments=11

--- checkpoint after 125 runs | elapsed 4.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
2,0.7,1.3,0.75,10,0.889680,0.021816,2.32,3.0,6,6,7.32,11,4.0,1091.84,440.92,1152.00,241.12,78.24,293.88,25

[0126/1800] seed=25 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.889 deaths=6 segments=11
[0127/1800] seed=26 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.884 deaths=2 segments=7
[0128/1800] seed=27 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.833 deaths=2 segments=7
[0129/1800] seed=28 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.857 deaths=1 segments=6
[0130/1800] seed=29 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.888 deaths=6 segments=11
[0131/1800] seed=30 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.892 deaths=3 segments=8
[0132/1800] seed=31 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.870 deaths=4 segments=9
[0133/1800] seed=32 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=5 segments=10
[0134/1800] seed=33 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.868 deaths=4 segments=9
[0135/1800] seed=34 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.804 deaths=2 segments=7
[0136/1800] seed=35 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.827 deaths=0 segments=5
[0137/1800] seed=36 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.903 deaths=1 segments=6
[0138/1800] seed=37 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.904 deaths=4 segments=9
[0139/1800] seed=38 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.907 deaths=1 segments=6
[0140/1800] seed=39 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.896 deaths=3 segments=8
[0141/1800] seed=40 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.880 deaths=3 segments=8
[0142/1800] seed=41 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.903 deaths=3 segments=8
[0143/1800] seed=42 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.887 deaths=2 segments=7
[0144/1800] seed=43 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.830 deaths=3 segments=8
[0145/1800] seed=44 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.853 deaths=3 segments=8
[0146/1800] seed=45 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=3 segments=8
[0147/1800] seed=46 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.871 deaths=1 segments=6
[0148/1800] seed=47 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.842 deaths=4 segments=9
[0149/1800] seed=48 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.791 deaths=10 segments=15
[0150/1800] seed=49 decay=0.70 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=3 segments=8

--- checkpoint after 150 runs | elapsed 5.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0151/1800] seed=00 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.878 deaths=2 segments=7
[0152/1800] seed=01 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.885 deaths=0 segments=5
[0153/1800] seed=02 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.876 deaths=3 segments=8
[0154/1800] seed=03 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.892 deaths=3 segments=8
[0155/1800] seed=04 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.926 deaths=0 segments=5
[0156/1800] seed=05 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.879 deaths=3 segments=8
[0157/1800] seed=06 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.908 deaths=2 segments=7
[0158/1800] seed=07 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.894 deaths=0 segments=5
[0159/1800] seed=08 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.934 deaths=1 segments=6
[0160/1800] seed=09 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.873 deaths=3 segments=8
[0161/1800] seed=10 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.908 deaths=3 segments=8
[0162/1800] seed=11 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.874 deaths=2 segments=7
[0163/1800] seed=12 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.882 deaths=3 segments=8
[0164/1800] seed=13 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.888 deaths=2 segments=7
[0165/1800] seed=14 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.909 deaths=2 segments=7
[0166/1800] seed=15 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.896 deaths=3 segments=8
[0167/1800] seed=16 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.871 deaths=2 segments=7
[0168/1800] seed=17 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.911 deaths=1 segments=6
[0169/1800] seed=18 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.905 deaths=3 segments=8
[0170/1800] seed=19 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.861 deaths=0 segments=5
[0171/1800] seed=20 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.882 deaths=4 segments=9
[0172/1800] seed=21 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.899 deaths=6 segments=11
[0173/1800] seed=22 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.878 deaths=0 segments=5
[0174/1800] seed=23 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.860 deaths=3 segments=8
[0175/1800] seed=24 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.886 deaths=6 segments=11

--- checkpoint after 175 runs | elapsed 6.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
3,0.7,1.3,0.75,14,0.890189,0.018763,2.28,2.0,6,5,7.28,11,4.0,1090.48,435.36,1127.52,244.44,78.28,283.00,25
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0176/1800] seed=25 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.889 deaths=6 segments=11
[0177/1800] seed=26 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.926 deaths=1 segments=6
[0178/1800] seed=27 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.830 deaths=2 segments=7
[0179/1800] seed=28 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.876 deaths=2 segments=7
[0180/1800] seed=29 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.887 deaths=6 segments=11
[0181/1800] seed=30 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.854 deaths=6 segments=11
[0182/1800] seed=31 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.905 deaths=1 segments=6
[0183/1800] seed=32 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.843 deaths=7 segments=12
[0184/1800] seed=33 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.868 deaths=4 segments=9
[0185/1800] seed=34 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.804 deaths=2 segments=7
[0186/1800] seed=35 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.827 deaths=0 segments=5
[0187/1800] seed=36 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.873 deaths=5 segments=10
[0188/1800] seed=37 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.902 deaths=5 segments=10
[0189/1800] seed=38 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.907 deaths=1 segments=6
[0190/1800] seed=39 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.896 deaths=3 segments=8
[0191/1800] seed=40 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.880 deaths=3 segments=8
[0192/1800] seed=41 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.910 deaths=3 segments=8
[0193/1800] seed=42 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.870 deaths=3 segments=8
[0194/1800] seed=43 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.830 deaths=3 segments=8
[0195/1800] seed=44 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.853 deaths=3 segments=8
[0196/1800] seed=45 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.901 deaths=3 segments=8
[0197/1800] seed=46 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.890 deaths=1 segments=6
[0198/1800] seed=47 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.864 deaths=2 segments=7
[0199/1800] seed=48 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.893 deaths=4 segments=9
[0200/1800] seed=49 decay=0.70 fill=1.30 p=0.75 smellR=14 | comfort=0.887 deaths=2 segments=7

--- checkpoint after 200 runs | elapsed 7.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0201/1800] seed=00 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.812 deaths=6 segments=11
[0202/1800] seed=01 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.813 deaths=0 segments=5
[0203/1800] seed=02 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.846 deaths=3 segments=8
[0204/1800] seed=03 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.848 deaths=0 segments=5
[0205/1800] seed=04 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.855 deaths=0 segments=5
[0206/1800] seed=05 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.803 deaths=1 segments=6
[0207/1800] seed=06 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.841 deaths=1 segments=6
[0208/1800] seed=07 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.818 deaths=0 segments=5
[0209/1800] seed=08 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.801 deaths=2 segments=7
[0210/1800] seed=09 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.772 deaths=1 segments=6
[0211/1800] seed=10 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.799 deaths=0 segments=5
[0212/1800] seed=11 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.847 deaths=1 segments=6
[0213/1800] seed=12 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.867 deaths=3 segments=8
[0214/1800] seed=13 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.815 deaths=2 segments=7
[0215/1800] seed=14 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.840 deaths=0 segments=5
[0216/1800] seed=15 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=2 segments=7
[0217/1800] seed=16 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.803 deaths=1 segments=6
[0218/1800] seed=17 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.779 deaths=1 segments=6
[0219/1800] seed=18 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.889 deaths=0 segments=5
[0220/1800] seed=19 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.852 deaths=5 segments=10
[0221/1800] seed=20 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.838 deaths=2 segments=7
[0222/1800] seed=21 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=1 segments=6
[0223/1800] seed=22 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.864 deaths=3 segments=8
[0224/1800] seed=23 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.855 deaths=1 segments=6
[0225/1800] seed=24 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.746 deaths=5 segments=10

--- checkpoint after 225 runs | elapsed 8.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
4,0.7,1.6,0.55,10,0.825914,0.032929,1.64,1.0,6,7,6.64,11,4.0,1072.16,427.04,748.52,200.88,52.04,123.20,25
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0226/1800] seed=25 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.797 deaths=1 segments=6
[0227/1800] seed=26 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.779 deaths=2 segments=7
[0228/1800] seed=27 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.775 deaths=2 segments=7
[0229/1800] seed=28 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.798 deaths=1 segments=6
[0230/1800] seed=29 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.874 deaths=1 segments=6
[0231/1800] seed=30 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.818 deaths=5 segments=10
[0232/1800] seed=31 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.854 deaths=0 segments=5
[0233/1800] seed=32 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.847 deaths=2 segments=7
[0234/1800] seed=33 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.846 deaths=4 segments=9
[0235/1800] seed=34 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.820 deaths=4 segments=9
[0236/1800] seed=35 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.774 deaths=2 segments=7
[0237/1800] seed=36 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.815 deaths=6 segments=11
[0238/1800] seed=37 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.843 deaths=0 segments=5
[0239/1800] seed=38 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.801 deaths=2 segments=7
[0240/1800] seed=39 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.827 deaths=3 segments=8
[0241/1800] seed=40 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.830 deaths=2 segments=7
[0242/1800] seed=41 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.801 deaths=3 segments=8
[0243/1800] seed=42 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.828 deaths=3 segments=8
[0244/1800] seed=43 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.815 deaths=2 segments=7
[0245/1800] seed=44 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.833 deaths=2 segments=7
[0246/1800] seed=45 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.821 deaths=1 segments=6
[0247/1800] seed=46 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.784 deaths=3 segments=8
[0248/1800] seed=47 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.790 deaths=2 segments=7
[0249/1800] seed=48 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.811 deaths=1 segments=6
[0250/1800] seed=49 decay=0.70 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=0 segments=5

--- checkpoint after 250 runs | elapsed 9.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0251/1800] seed=00 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.812 deaths=6 segments=11
[0252/1800] seed=01 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.813 deaths=0 segments=5
[0253/1800] seed=02 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.846 deaths=3 segments=8
[0254/1800] seed=03 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.823 deaths=2 segments=7
[0255/1800] seed=04 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.863 deaths=0 segments=5
[0256/1800] seed=05 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.803 deaths=1 segments=6
[0257/1800] seed=06 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.841 deaths=1 segments=6
[0258/1800] seed=07 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.818 deaths=0 segments=5
[0259/1800] seed=08 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.801 deaths=2 segments=7
[0260/1800] seed=09 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.772 deaths=1 segments=6
[0261/1800] seed=10 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.801 deaths=0 segments=5
[0262/1800] seed=11 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.847 deaths=1 segments=6
[0263/1800] seed=12 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.824 deaths=2 segments=7
[0264/1800] seed=13 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.816 deaths=2 segments=7
[0265/1800] seed=14 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.840 deaths=0 segments=5
[0266/1800] seed=15 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.809 deaths=2 segments=7
[0267/1800] seed=16 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.803 deaths=1 segments=6
[0268/1800] seed=17 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.779 deaths=1 segments=6
[0269/1800] seed=18 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.889 deaths=0 segments=5
[0270/1800] seed=19 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.862 deaths=1 segments=6
[0271/1800] seed=20 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.839 deaths=1 segments=6
[0272/1800] seed=21 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.799 deaths=0 segments=5
[0273/1800] seed=22 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.864 deaths=3 segments=8
[0274/1800] seed=23 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.814 deaths=0 segments=5
[0275/1800] seed=24 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.763 deaths=5 segments=10

--- checkpoint after 275 runs | elapsed 10.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
5,0.7,1.6,0.55,14,0.821640,0.030407,1.40,1.0,6,8,6.40,11,4.0,1050.44,426.00,719.04,199.72,51.56,116.04,25
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0276/1800] seed=25 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.797 deaths=1 segments=6
[0277/1800] seed=26 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.873 deaths=0 segments=5
[0278/1800] seed=27 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.826 deaths=1 segments=6
[0279/1800] seed=28 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.798 deaths=1 segments=6
[0280/1800] seed=29 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.874 deaths=1 segments=6
[0281/1800] seed=30 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.781 deaths=3 segments=8
[0282/1800] seed=31 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.831 deaths=3 segments=8
[0283/1800] seed=32 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.831 deaths=2 segments=7
[0284/1800] seed=33 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.846 deaths=4 segments=9
[0285/1800] seed=34 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.747 deaths=2 segments=7
[0286/1800] seed=35 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.772 deaths=1 segments=6
[0287/1800] seed=36 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.825 deaths=2 segments=7
[0288/1800] seed=37 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.843 deaths=0 segments=5
[0289/1800] seed=38 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.801 deaths=2 segments=7
[0290/1800] seed=39 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.816 deaths=4 segments=9
[0291/1800] seed=40 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=2 segments=7
[0292/1800] seed=41 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.815 deaths=1 segments=6
[0293/1800] seed=42 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.828 deaths=3 segments=8
[0294/1800] seed=43 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=2 segments=7
[0295/1800] seed=44 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.833 deaths=2 segments=7
[0296/1800] seed=45 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.821 deaths=1 segments=6
[0297/1800] seed=46 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.784 deaths=3 segments=8
[0298/1800] seed=47 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.791 deaths=3 segments=8
[0299/1800] seed=48 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.820 deaths=1 segments=6
[0300/1800] seed=49 decay=0.70 fill=1.60 p=0.55 smellR=14 | comfort=0.822 deaths=0 segments=5

--- checkpoint after 300 runs | elapsed 11.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0301/1800] seed=00 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=2 segments=7
[0302/1800] seed=01 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.780 deaths=3 segments=8
[0303/1800] seed=02 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.806 deaths=3 segments=8
[0304/1800] seed=03 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.784 deaths=6 segments=11
[0305/1800] seed=04 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.841 deaths=0 segments=5
[0306/1800] seed=05 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.818 deaths=2 segments=7
[0307/1800] seed=06 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=0 segments=5
[0308/1800] seed=07 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.783 deaths=8 segments=13
[0309/1800] seed=08 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.873 deaths=1 segments=6
[0310/1800] seed=09 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.811 deaths=3 segments=8
[0311/1800] seed=10 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.781 deaths=3 segments=8
[0312/1800] seed=11 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=2 segments=7
[0313/1800] seed=12 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.866 deaths=3 segments=8
[0314/1800] seed=13 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.853 deaths=3 segments=8
[0315/1800] seed=14 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.846 deaths=4 segments=9
[0316/1800] seed=15 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.775 deaths=4 segments=9
[0317/1800] seed=16 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.809 deaths=2 segments=7
[0318/1800] seed=17 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.797 deaths=1 segments=6
[0319/1800] seed=18 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.816 deaths=3 segments=8
[0320/1800] seed=19 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.814 deaths=0 segments=5
[0321/1800] seed=20 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.805 deaths=4 segments=9
[0322/1800] seed=21 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.850 deaths=3 segments=8
[0323/1800] seed=22 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=0 segments=5
[0324/1800] seed=23 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.810 deaths=5 segments=10
[0325/1800] seed=24 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.792 deaths=4 segments=9

--- checkpoint after 325 runs | elapsed 12.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.816087,0.027176,2.76,3.0,8,4,7.76,13,4.0,1059.76,410.60,1129.52,240.92,77.00,287.28,25

[0326/1800] seed=25 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.809 deaths=7 segments=12
[0327/1800] seed=26 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.840 deaths=2 segments=7
[0328/1800] seed=27 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.820 deaths=3 segments=8
[0329/1800] seed=28 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.807 deaths=1 segments=6
[0330/1800] seed=29 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.812 deaths=6 segments=11
[0331/1800] seed=30 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.793 deaths=3 segments=8
[0332/1800] seed=31 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.804 deaths=4 segments=9
[0333/1800] seed=32 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.792 deaths=6 segments=11
[0334/1800] seed=33 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.805 deaths=1 segments=6
[0335/1800] seed=34 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.781 deaths=3 segments=8
[0336/1800] seed=35 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.765 deaths=0 segments=5
[0337/1800] seed=36 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.847 deaths=1 segments=6
[0338/1800] seed=37 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.840 deaths=4 segments=9
[0339/1800] seed=38 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=1 segments=6
[0340/1800] seed=39 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.846 deaths=3 segments=8
[0341/1800] seed=40 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=1 segments=6
[0342/1800] seed=41 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.842 deaths=0 segments=5
[0343/1800] seed=42 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.814 deaths=3 segments=8
[0344/1800] seed=43 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.779 deaths=3 segments=8
[0345/1800] seed=44 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.788 deaths=4 segments=9
[0346/1800] seed=45 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.828 deaths=6 segments=11
[0347/1800] seed=46 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.859 deaths=2 segments=7
[0348/1800] seed=47 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.793 deaths=4 segments=9
[0349/1800] seed=48 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.723 deaths=10 segments=15
[0350/1800] seed=49 decay=0.70 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=3 segments=8

--- checkpoint after 350 runs | elapsed 13.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50

[0351/1800] seed=00 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=2 segments=7
[0352/1800] seed=01 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.780 deaths=3 segments=8
[0353/1800] seed=02 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.806 deaths=3 segments=8
[0354/1800] seed=03 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=3 segments=8
[0355/1800] seed=04 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.865 deaths=0 segments=5
[0356/1800] seed=05 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.810 deaths=3 segments=8
[0357/1800] seed=06 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.828 deaths=2 segments=7
[0358/1800] seed=07 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.783 deaths=8 segments=13
[0359/1800] seed=08 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.873 deaths=1 segments=6
[0360/1800] seed=09 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.811 deaths=3 segments=8
[0361/1800] seed=10 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.832 deaths=3 segments=8
[0362/1800] seed=11 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.821 deaths=2 segments=7
[0363/1800] seed=12 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.804 deaths=3 segments=8
[0364/1800] seed=13 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.811 deaths=8 segments=13
[0365/1800] seed=14 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.846 deaths=4 segments=9
[0366/1800] seed=15 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=3 segments=8
[0367/1800] seed=16 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.809 deaths=2 segments=7
[0368/1800] seed=17 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.797 deaths=1 segments=6
[0369/1800] seed=18 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.816 deaths=3 segments=8
[0370/1800] seed=19 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.814 deaths=0 segments=5
[0371/1800] seed=20 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=4 segments=9
[0372/1800] seed=21 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.802 deaths=4 segments=9
[0373/1800] seed=22 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.821 deaths=0 segments=5
[0374/1800] seed=23 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.790 deaths=3 segments=8
[0375/1800] seed=24 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.792 deaths=4 segments=9

--- checkpoint after 375 runs | elapsed 13.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
7,0.7,1.6,0.75,14,0.817364,0.022871,2.88,3.0,8,3,7.88,13,4.0,1054.68,426.16,1097.32,244.04,77.12,273.24,25
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50

[0376/1800] seed=25 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.802 deaths=7 segments=12
[0377/1800] seed=26 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.832 deaths=4 segments=9
[0378/1800] seed=27 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.841 deaths=3 segments=8
[0379/1800] seed=28 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.802 deaths=2 segments=7
[0380/1800] seed=29 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.800 deaths=6 segments=11
[0381/1800] seed=30 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.793 deaths=3 segments=8
[0382/1800] seed=31 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.807 deaths=2 segments=7
[0383/1800] seed=32 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.746 deaths=9 segments=14
[0384/1800] seed=33 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.805 deaths=1 segments=6
[0385/1800] seed=34 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.782 deaths=3 segments=8
[0386/1800] seed=35 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.765 deaths=0 segments=5
[0387/1800] seed=36 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.825 deaths=1 segments=6
[0388/1800] seed=37 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=4 segments=9
[0389/1800] seed=38 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.823 deaths=1 segments=6
[0390/1800] seed=39 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.846 deaths=3 segments=8
[0391/1800] seed=40 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.801 deaths=1 segments=6
[0392/1800] seed=41 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.803 deaths=4 segments=9
[0393/1800] seed=42 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.814 deaths=3 segments=8
[0394/1800] seed=43 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.779 deaths=3 segments=8
[0395/1800] seed=44 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.798 deaths=4 segments=9
[0396/1800] seed=45 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.818 deaths=7 segments=12
[0397/1800] seed=46 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.859 deaths=2 segments=7
[0398/1800] seed=47 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.814 deaths=2 segments=7
[0399/1800] seed=48 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.802 deaths=4 segments=9
[0400/1800] seed=49 decay=0.70 fill=1.60 p=0.75 smellR=14 | comfort=0.840 deaths=2 segments=7

--- checkpoint after 400 runs | elapsed 14.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50

[0401/1800] seed=00 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.731 deaths=6 segments=11
[0402/1800] seed=01 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.746 deaths=1 segments=6
[0403/1800] seed=02 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=3 segments=8
[0404/1800] seed=03 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.761 deaths=0 segments=5
[0405/1800] seed=04 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.764 deaths=0 segments=5
[0406/1800] seed=05 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.715 deaths=3 segments=8
[0407/1800] seed=06 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.763 deaths=1 segments=6
[0408/1800] seed=07 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.741 deaths=0 segments=5
[0409/1800] seed=08 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.713 deaths=2 segments=7
[0410/1800] seed=09 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.707 deaths=2 segments=7
[0411/1800] seed=10 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=0 segments=5
[0412/1800] seed=11 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.735 deaths=1 segments=6
[0413/1800] seed=12 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.773 deaths=3 segments=8
[0414/1800] seed=13 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.726 deaths=2 segments=7
[0415/1800] seed=14 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.749 deaths=0 segments=5
[0416/1800] seed=15 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=1 segments=6
[0417/1800] seed=16 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.717 deaths=1 segments=6
[0418/1800] seed=17 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.718 deaths=1 segments=6
[0419/1800] seed=18 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.759 deaths=0 segments=5
[0420/1800] seed=19 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.768 deaths=2 segments=7
[0421/1800] seed=20 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.744 deaths=2 segments=7
[0422/1800] seed=21 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.749 deaths=1 segments=6
[0423/1800] seed=22 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=0 segments=5
[0424/1800] seed=23 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.744 deaths=1 segments=6
[0425/1800] seed=24 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.734 deaths=2 segments=7

--- checkpoint after 425 runs | elapsed 15.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
8,0.7,1.9,0.55,10,0.741399,0.018280,1.40,1.0,6,7,6.40,11,4.0,1034.76,469.24,744.04,198.44,51.92,122.28,25
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50

[0426/1800] seed=25 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.719 deaths=1 segments=6
[0427/1800] seed=26 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.756 deaths=1 segments=6
[0428/1800] seed=27 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.693 deaths=1 segments=6
[0429/1800] seed=28 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.727 deaths=1 segments=6
[0430/1800] seed=29 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=5 segments=10
[0431/1800] seed=30 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.753 deaths=7 segments=12
[0432/1800] seed=31 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=0 segments=5
[0433/1800] seed=32 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=2 segments=7
[0434/1800] seed=33 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.749 deaths=4 segments=9
[0435/1800] seed=34 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.715 deaths=0 segments=5
[0436/1800] seed=35 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.711 deaths=2 segments=7
[0437/1800] seed=36 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=6 segments=11
[0438/1800] seed=37 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.756 deaths=0 segments=5
[0439/1800] seed=38 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.727 deaths=2 segments=7
[0440/1800] seed=39 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=1 segments=6
[0441/1800] seed=40 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=2 segments=7
[0442/1800] seed=41 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.704 deaths=3 segments=8
[0443/1800] seed=42 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.736 deaths=3 segments=8
[0444/1800] seed=43 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.734 deaths=2 segments=7
[0445/1800] seed=44 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.774 deaths=1 segments=6
[0446/1800] seed=45 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.727 deaths=0 segments=5
[0447/1800] seed=46 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.710 deaths=3 segments=8
[0448/1800] seed=47 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.714 deaths=2 segments=7
[0449/1800] seed=48 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=0 segments=5
[0450/1800] seed=49 decay=0.70 fill=1.90 p=0.55 smellR=10 | comfort=0.723 deaths=1 segments=6

--- checkpoint after 450 runs | elapsed 16.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50

[0451/1800] seed=00 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.731 deaths=6 segments=11
[0452/1800] seed=01 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=1 segments=6
[0453/1800] seed=02 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.748 deaths=3 segments=8
[0454/1800] seed=03 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.783 deaths=0 segments=5
[0455/1800] seed=04 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.770 deaths=0 segments=5
[0456/1800] seed=05 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.715 deaths=3 segments=8
[0457/1800] seed=06 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.763 deaths=1 segments=6
[0458/1800] seed=07 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.741 deaths=0 segments=5
[0459/1800] seed=08 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.713 deaths=2 segments=7
[0460/1800] seed=09 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.691 deaths=4 segments=9
[0461/1800] seed=10 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.739 deaths=0 segments=5
[0462/1800] seed=11 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.735 deaths=1 segments=6
[0463/1800] seed=12 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.742 deaths=2 segments=7
[0464/1800] seed=13 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.725 deaths=2 segments=7
[0465/1800] seed=14 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.749 deaths=0 segments=5
[0466/1800] seed=15 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.749 deaths=1 segments=6
[0467/1800] seed=16 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.718 deaths=1 segments=6
[0468/1800] seed=17 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.718 deaths=1 segments=6
[0469/1800] seed=18 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.759 deaths=0 segments=5
[0470/1800] seed=19 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.754 deaths=1 segments=6
[0471/1800] seed=20 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.727 deaths=1 segments=6
[0472/1800] seed=21 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.763 deaths=4 segments=9
[0473/1800] seed=22 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.754 deaths=0 segments=5
[0474/1800] seed=23 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.742 deaths=4 segments=9
[0475/1800] seed=24 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.698 deaths=5 segments=10

--- checkpoint after 475 runs | elapsed 17.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.738901,0.022115,1.72,1.0,6,7,6.72,11,4.0,1021.32,469.92,741.44,203.88,54.44,120.04,25
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50

[0476/1800] seed=25 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.719 deaths=1 segments=6
[0477/1800] seed=26 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.754 deaths=0 segments=5
[0478/1800] seed=27 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.693 deaths=2 segments=7
[0479/1800] seed=28 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.727 deaths=1 segments=6
[0480/1800] seed=29 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.729 deaths=1 segments=6
[0481/1800] seed=30 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.747 deaths=7 segments=12
[0482/1800] seed=31 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.735 deaths=3 segments=8
[0483/1800] seed=32 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.760 deaths=1 segments=6
[0484/1800] seed=33 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=4 segments=9
[0485/1800] seed=34 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.715 deaths=3 segments=8
[0486/1800] seed=35 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.710 deaths=1 segments=6
[0487/1800] seed=36 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.688 deaths=7 segments=12
[0488/1800] seed=37 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.756 deaths=0 segments=5
[0489/1800] seed=38 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.727 deaths=2 segments=7
[0490/1800] seed=39 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.763 deaths=1 segments=6
[0491/1800] seed=40 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.748 deaths=2 segments=7
[0492/1800] seed=41 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.720 deaths=1 segments=6
[0493/1800] seed=42 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.736 deaths=3 segments=8
[0494/1800] seed=43 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.759 deaths=2 segments=7
[0495/1800] seed=44 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.763 deaths=0 segments=5
[0496/1800] seed=45 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.734 deaths=0 segments=5
[0497/1800] seed=46 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.710 deaths=3 segments=8
[0498/1800] seed=47 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.717 deaths=3 segments=8
[0499/1800] seed=48 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.742 deaths=0 segments=5
[0500/1800] seed=49 decay=0.70 fill=1.90 p=0.55 smellR=14 | comfort=0.723 deaths=1 segments=6

--- checkpoint after 500 runs | elapsed 18.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50

[0501/1800] seed=00 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.754 deaths=2 segments=7
[0502/1800] seed=01 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.731 deaths=1 segments=6
[0503/1800] seed=02 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.722 deaths=3 segments=8
[0504/1800] seed=03 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.773 deaths=1 segments=6
[0505/1800] seed=04 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.746 deaths=1 segments=6
[0506/1800] seed=05 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.725 deaths=2 segments=7
[0507/1800] seed=06 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.735 deaths=0 segments=5
[0508/1800] seed=07 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.751 deaths=2 segments=7
[0509/1800] seed=08 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.756 deaths=1 segments=6
[0510/1800] seed=09 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.757 deaths=1 segments=6
[0511/1800] seed=10 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=3 segments=8
[0512/1800] seed=11 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=2 segments=7
[0513/1800] seed=12 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.770 deaths=3 segments=8
[0514/1800] seed=13 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=3 segments=8
[0515/1800] seed=14 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.688 deaths=4 segments=9
[0516/1800] seed=15 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.737 deaths=6 segments=11
[0517/1800] seed=16 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.721 deaths=3 segments=8
[0518/1800] seed=17 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.708 deaths=2 segments=7
[0519/1800] seed=18 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.728 deaths=3 segments=8
[0520/1800] seed=19 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.729 deaths=0 segments=5
[0521/1800] seed=20 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=4 segments=9
[0522/1800] seed=21 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.757 deaths=3 segments=8
[0523/1800] seed=22 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.749 deaths=0 segments=5
[0524/1800] seed=23 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.730 deaths=5 segments=10
[0525/1800] seed=24 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.704 deaths=4 segments=9

--- checkpoint after 525 runs | elapsed 19.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
10,0.7,1.9,0.75,10,0.735222,0.020843,2.36,2.0,6,3,7.36,11,4.0,973.88,473.28,1108.12,240.16,79.88,277.60,25
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50

[0526/1800] seed=25 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.693 deaths=7 segments=12
[0527/1800] seed=26 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.735 deaths=3 segments=8
[0528/1800] seed=27 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.728 deaths=0 segments=5
[0529/1800] seed=28 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.701 deaths=5 segments=10
[0530/1800] seed=29 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.726 deaths=3 segments=8
[0531/1800] seed=30 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.743 deaths=5 segments=10
[0532/1800] seed=31 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.708 deaths=5 segments=10
[0533/1800] seed=32 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.707 deaths=1 segments=6
[0534/1800] seed=33 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.722 deaths=1 segments=6
[0535/1800] seed=34 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.716 deaths=5 segments=10
[0536/1800] seed=35 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.702 deaths=0 segments=5
[0537/1800] seed=36 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.734 deaths=1 segments=6
[0538/1800] seed=37 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.738 deaths=2 segments=7
[0539/1800] seed=38 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.710 deaths=3 segments=8
[0540/1800] seed=39 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.751 deaths=3 segments=8
[0541/1800] seed=40 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.739 deaths=1 segments=6
[0542/1800] seed=41 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.725 deaths=3 segments=8
[0543/1800] seed=42 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.727 deaths=0 segments=5
[0544/1800] seed=43 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.717 deaths=3 segments=8
[0545/1800] seed=44 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=4 segments=9
[0546/1800] seed=45 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.737 deaths=6 segments=11
[0547/1800] seed=46 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.731 deaths=3 segments=8
[0548/1800] seed=47 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.725 deaths=4 segments=9
[0549/1800] seed=48 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.710 deaths=2 segments=7
[0550/1800] seed=49 decay=0.70 fill=1.90 p=0.75 smellR=10 | comfort=0.740 deaths=3 segments=8

--- checkpoint after 550 runs | elapsed 20.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50

[0551/1800] seed=00 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.754 deaths=2 segments=7
[0552/1800] seed=01 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=1 segments=6
[0553/1800] seed=02 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.722 deaths=3 segments=8
[0554/1800] seed=03 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.757 deaths=3 segments=8
[0555/1800] seed=04 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.746 deaths=1 segments=6
[0556/1800] seed=05 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.730 deaths=3 segments=8
[0557/1800] seed=06 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.721 deaths=2 segments=7
[0558/1800] seed=07 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.751 deaths=2 segments=7
[0559/1800] seed=08 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.756 deaths=1 segments=6
[0560/1800] seed=09 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.757 deaths=1 segments=6
[0561/1800] seed=10 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.704 deaths=3 segments=8
[0562/1800] seed=11 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.703 deaths=2 segments=7
[0563/1800] seed=12 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.724 deaths=3 segments=8
[0564/1800] seed=13 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.704 deaths=8 segments=13
[0565/1800] seed=14 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.688 deaths=4 segments=9
[0566/1800] seed=15 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.736 deaths=3 segments=8
[0567/1800] seed=16 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.711 deaths=4 segments=9
[0568/1800] seed=17 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.708 deaths=2 segments=7
[0569/1800] seed=18 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.728 deaths=3 segments=8
[0570/1800] seed=19 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.729 deaths=0 segments=5
[0571/1800] seed=20 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=4 segments=9
[0572/1800] seed=21 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.729 deaths=0 segments=5
[0573/1800] seed=22 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=0 segments=5
[0574/1800] seed=23 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.699 deaths=3 segments=8
[0575/1800] seed=24 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.704 deaths=4 segments=9

--- checkpoint after 575 runs | elapsed 21.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
11,0.7,1.9,0.75,14,0.727567,0.020903,2.48,3.0,8,3,7.48,13,4.0,1007.00,454.16,1094.04,241.44,78.04,273.16,25
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0576/1800] seed=25 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.693 deaths=7 segments=12
[0577/1800] seed=26 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.753 deaths=4 segments=9
[0578/1800] seed=27 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.728 deaths=0 segments=5
[0579/1800] seed=28 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.701 deaths=5 segments=10
[0580/1800] seed=29 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.726 deaths=3 segments=8
[0581/1800] seed=30 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.744 deaths=4 segments=9
[0582/1800] seed=31 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.704 deaths=1 segments=6
[0583/1800] seed=32 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.707 deaths=1 segments=6
[0584/1800] seed=33 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.722 deaths=1 segments=6
[0585/1800] seed=34 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.707 deaths=1 segments=6
[0586/1800] seed=35 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.702 deaths=0 segments=5
[0587/1800] seed=36 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.712 deaths=3 segments=8
[0588/1800] seed=37 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.733 deaths=3 segments=8
[0589/1800] seed=38 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.732 deaths=1 segments=6
[0590/1800] seed=39 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.751 deaths=3 segments=8
[0591/1800] seed=40 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.740 deaths=1 segments=6
[0592/1800] seed=41 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.725 deaths=3 segments=8
[0593/1800] seed=42 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.727 deaths=0 segments=5
[0594/1800] seed=43 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.717 deaths=3 segments=8
[0595/1800] seed=44 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.703 deaths=4 segments=9
[0596/1800] seed=45 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.728 deaths=7 segments=12
[0597/1800] seed=46 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=3 segments=8
[0598/1800] seed=47 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.743 deaths=2 segments=7
[0599/1800] seed=48 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.719 deaths=5 segments=10
[0600/1800] seed=49 decay=0.70 fill=1.90 p=0.75 smellR=14 | comfort=0.763 deaths=2 segments=7

--- checkpoint after 600 runs | elapsed 22.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0601/1800] seed=00 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.859 deaths=2 segments=7
[0602/1800] seed=01 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.907 deaths=6 segments=11
[0603/1800] seed=02 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.889 deaths=1 segments=6
[0604/1800] seed=03 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=3 segments=8
[0605/1800] seed=04 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.912 deaths=0 segments=5
[0606/1800] seed=05 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.924 deaths=2 segments=7
[0607/1800] seed=06 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.911 deaths=1 segments=6
[0608/1800] seed=07 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.888 deaths=0 segments=5
[0609/1800] seed=08 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.931 deaths=2 segments=7
[0610/1800] seed=09 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.904 deaths=3 segments=8
[0611/1800] seed=10 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.868 deaths=3 segments=8
[0612/1800] seed=11 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.897 deaths=2 segments=7
[0613/1800] seed=12 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.931 deaths=0 segments=5
[0614/1800] seed=13 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.873 deaths=8 segments=13
[0615/1800] seed=14 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.920 deaths=5 segments=10
[0616/1800] seed=15 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.839 deaths=6 segments=11
[0617/1800] seed=16 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.877 deaths=6 segments=11
[0618/1800] seed=17 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.871 deaths=3 segments=8
[0619/1800] seed=18 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.873 deaths=3 segments=8
[0620/1800] seed=19 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.882 deaths=1 segments=6
[0621/1800] seed=20 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.884 deaths=4 segments=9
[0622/1800] seed=21 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.907 deaths=4 segments=9
[0623/1800] seed=22 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.894 deaths=3 segments=8
[0624/1800] seed=23 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.910 deaths=0 segments=5
[0625/1800] seed=24 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.869 deaths=1 segments=6

--- checkpoint after 625 runs | elapsed 23.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50

[0626/1800] seed=25 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.870 deaths=1 segments=6
[0627/1800] seed=26 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.899 deaths=2 segments=7
[0628/1800] seed=27 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.924 deaths=1 segments=6
[0629/1800] seed=28 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.935 deaths=2 segments=7
[0630/1800] seed=29 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.881 deaths=1 segments=6
[0631/1800] seed=30 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.909 deaths=5 segments=10
[0632/1800] seed=31 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.929 deaths=1 segments=6
[0633/1800] seed=32 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.895 deaths=1 segments=6
[0634/1800] seed=33 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.843 deaths=2 segments=7
[0635/1800] seed=34 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.866 deaths=2 segments=7
[0636/1800] seed=35 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.908 deaths=2 segments=7
[0637/1800] seed=36 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.874 deaths=4 segments=9
[0638/1800] seed=37 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.885 deaths=2 segments=7
[0639/1800] seed=38 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.895 deaths=2 segments=7
[0640/1800] seed=39 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.867 deaths=5 segments=10
[0641/1800] seed=40 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.873 deaths=1 segments=6
[0642/1800] seed=41 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.906 deaths=3 segments=8
[0643/1800] seed=42 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.919 deaths=0 segments=5
[0644/1800] seed=43 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.911 deaths=3 segments=8
[0645/1800] seed=44 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.936 deaths=1 segments=6
[0646/1800] seed=45 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.863 deaths=2 segments=7
[0647/1800] seed=46 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.894 deaths=6 segments=11
[0648/1800] seed=47 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.932 deaths=0 segments=5
[0649/1800] seed=48 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.883 deaths=1 segments=6
[0650/1800] seed=49 decay=0.80 fill=1.30 p=0.55 smellR=10 | comfort=0.882 deaths=0 segments=5

--- checkpoint after 650 runs | elapsed 24.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50

[0651/1800] seed=00 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.844 deaths=3 segments=8
[0652/1800] seed=01 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.907 deaths=6 segments=11
[0653/1800] seed=02 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.890 deaths=1 segments=6
[0654/1800] seed=03 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.920 deaths=0 segments=5
[0655/1800] seed=04 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.890 deaths=4 segments=9
[0656/1800] seed=05 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.924 deaths=2 segments=7
[0657/1800] seed=06 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.910 deaths=1 segments=6
[0658/1800] seed=07 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.888 deaths=0 segments=5
[0659/1800] seed=08 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.931 deaths=2 segments=7
[0660/1800] seed=09 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.902 deaths=3 segments=8
[0661/1800] seed=10 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.868 deaths=3 segments=8
[0662/1800] seed=11 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.897 deaths=2 segments=7
[0663/1800] seed=12 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.931 deaths=0 segments=5
[0664/1800] seed=13 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.890 deaths=1 segments=6
[0665/1800] seed=14 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.913 deaths=5 segments=10
[0666/1800] seed=15 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.923 deaths=3 segments=8
[0667/1800] seed=16 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.855 deaths=5 segments=10
[0668/1800] seed=17 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.873 deaths=4 segments=9
[0669/1800] seed=18 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.885 deaths=3 segments=8
[0670/1800] seed=19 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.921 deaths=2 segments=7
[0671/1800] seed=20 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.870 deaths=3 segments=8
[0672/1800] seed=21 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.897 deaths=0 segments=5
[0673/1800] seed=22 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.894 deaths=3 segments=8
[0674/1800] seed=23 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.896 deaths=2 segments=7
[0675/1800] seed=24 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.869 deaths=1 segments=6

--- checkpoint after 675 runs | elapsed 25.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.895528,0.023512,2.36,2.0,6,4,7.36,11,4.0,1152.08,469.84,733.76,209.08,53.96,113.12,25
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0676/1800] seed=25 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.924 deaths=2 segments=7
[0677/1800] seed=26 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.884 deaths=2 segments=7
[0678/1800] seed=27 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.920 deaths=1 segments=6
[0679/1800] seed=28 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.936 deaths=2 segments=7
[0680/1800] seed=29 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=1 segments=6
[0681/1800] seed=30 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.894 deaths=4 segments=9
[0682/1800] seed=31 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.891 deaths=4 segments=9
[0683/1800] seed=32 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.895 deaths=1 segments=6
[0684/1800] seed=33 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.843 deaths=2 segments=7
[0685/1800] seed=34 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.915 deaths=1 segments=6
[0686/1800] seed=35 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.909 deaths=2 segments=7
[0687/1800] seed=36 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.872 deaths=3 segments=8
[0688/1800] seed=37 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.885 deaths=2 segments=7
[0689/1800] seed=38 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.901 deaths=2 segments=7
[0690/1800] seed=39 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.873 deaths=2 segments=7
[0691/1800] seed=40 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.873 deaths=1 segments=6
[0692/1800] seed=41 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.906 deaths=3 segments=8
[0693/1800] seed=42 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.919 deaths=0 segments=5
[0694/1800] seed=43 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.909 deaths=3 segments=8
[0695/1800] seed=44 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.940 deaths=1 segments=6
[0696/1800] seed=45 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.879 deaths=2 segments=7
[0697/1800] seed=46 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.891 deaths=6 segments=11
[0698/1800] seed=47 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.932 deaths=0 segments=5
[0699/1800] seed=48 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.883 deaths=1 segments=6
[0700/1800] seed=49 decay=0.80 fill=1.30 p=0.55 smellR=14 | comfort=0.882 deaths=0 segments=5

--- checkpoint after 700 runs | elapsed 25.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0701/1800] seed=00 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.837 deaths=7 segments=12
[0702/1800] seed=01 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.884 deaths=3 segments=8
[0703/1800] seed=02 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.871 deaths=3 segments=8
[0704/1800] seed=03 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.851 deaths=11 segments=16
[0705/1800] seed=04 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.887 deaths=3 segments=8
[0706/1800] seed=05 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.913 deaths=1 segments=6
[0707/1800] seed=06 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.915 deaths=1 segments=6
[0708/1800] seed=07 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.906 deaths=5 segments=10
[0709/1800] seed=08 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.896 deaths=2 segments=7
[0710/1800] seed=09 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.897 deaths=2 segments=7
[0711/1800] seed=10 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.914 deaths=1 segments=6
[0712/1800] seed=11 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.877 deaths=3 segments=8
[0713/1800] seed=12 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.865 deaths=5 segments=10
[0714/1800] seed=13 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=6 segments=11
[0715/1800] seed=14 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.875 deaths=2 segments=7
[0716/1800] seed=15 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.896 deaths=1 segments=6
[0717/1800] seed=16 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.902 deaths=2 segments=7
[0718/1800] seed=17 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.903 deaths=3 segments=8
[0719/1800] seed=18 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.869 deaths=4 segments=9
[0720/1800] seed=19 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.887 deaths=1 segments=6
[0721/1800] seed=20 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.929 deaths=0 segments=5
[0722/1800] seed=21 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.909 deaths=4 segments=9
[0723/1800] seed=22 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.878 deaths=4 segments=9
[0724/1800] seed=23 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=3 segments=8
[0725/1800] seed=24 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.906 deaths=2 segments=7

--- checkpoint after 725 runs | elapsed 26.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0726/1800] seed=25 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.938 deaths=2 segments=7
[0727/1800] seed=26 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=2 segments=7
[0728/1800] seed=27 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.864 deaths=4 segments=9
[0729/1800] seed=28 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.873 deaths=5 segments=10
[0730/1800] seed=29 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.838 deaths=3 segments=8
[0731/1800] seed=30 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=1 segments=6
[0732/1800] seed=31 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.891 deaths=3 segments=8
[0733/1800] seed=32 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.866 deaths=3 segments=8
[0734/1800] seed=33 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.871 deaths=1 segments=6
[0735/1800] seed=34 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.887 deaths=2 segments=7
[0736/1800] seed=35 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.844 deaths=3 segments=8
[0737/1800] seed=36 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.869 deaths=3 segments=8
[0738/1800] seed=37 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.851 deaths=5 segments=10
[0739/1800] seed=38 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.886 deaths=2 segments=7
[0740/1800] seed=39 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.881 deaths=3 segments=8
[0741/1800] seed=40 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.842 deaths=8 segments=13
[0742/1800] seed=41 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.888 deaths=2 segments=7
[0743/1800] seed=42 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=1 segments=6
[0744/1800] seed=43 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.811 deaths=11 segments=16
[0745/1800] seed=44 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.842 deaths=10 segments=15
[0746/1800] seed=45 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.885 deaths=2 segments=7
[0747/1800] seed=46 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.909 deaths=3 segments=8
[0748/1800] seed=47 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.891 deaths=3 segments=8
[0749/1800] seed=48 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.916 deaths=0 segments=5
[0750/1800] seed=49 decay=0.80 fill=1.30 p=0.75 smellR=10 | comfort=0.864 deaths=4 segments=9

--- checkpoint after 750 runs | elapsed 27.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0751/1800] seed=00 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.885 deaths=4 segments=9
[0752/1800] seed=01 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.862 deaths=2 segments=7
[0753/1800] seed=02 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.894 deaths=3 segments=8
[0754/1800] seed=03 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.869 deaths=3 segments=8
[0755/1800] seed=04 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.887 deaths=3 segments=8
[0756/1800] seed=05 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.913 deaths=1 segments=6
[0757/1800] seed=06 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.929 deaths=1 segments=6
[0758/1800] seed=07 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.903 deaths=2 segments=7
[0759/1800] seed=08 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.896 deaths=2 segments=7
[0760/1800] seed=09 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.887 deaths=4 segments=9
[0761/1800] seed=10 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.914 deaths=1 segments=6
[0762/1800] seed=11 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.897 deaths=6 segments=11
[0763/1800] seed=12 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.905 deaths=2 segments=7
[0764/1800] seed=13 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.874 deaths=7 segments=12
[0765/1800] seed=14 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.875 deaths=2 segments=7
[0766/1800] seed=15 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.880 deaths=5 segments=10
[0767/1800] seed=16 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.902 deaths=2 segments=7
[0768/1800] seed=17 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.890 deaths=4 segments=9
[0769/1800] seed=18 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.869 deaths=4 segments=9
[0770/1800] seed=19 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.871 deaths=1 segments=6
[0771/1800] seed=20 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.929 deaths=0 segments=5
[0772/1800] seed=21 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.874 deaths=3 segments=8
[0773/1800] seed=22 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.880 deaths=5 segments=10
[0774/1800] seed=23 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.880 deaths=3 segments=8
[0775/1800] seed=24 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.906 deaths=2 segments=7

--- checkpoint after 775 runs | elapsed 28.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0776/1800] seed=25 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.938 deaths=2 segments=7
[0777/1800] seed=26 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.920 deaths=3 segments=8
[0778/1800] seed=27 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.864 deaths=4 segments=9
[0779/1800] seed=28 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.872 deaths=5 segments=10
[0780/1800] seed=29 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.905 deaths=0 segments=5
[0781/1800] seed=30 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.897 deaths=1 segments=6
[0782/1800] seed=31 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.882 deaths=2 segments=7
[0783/1800] seed=32 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.881 deaths=6 segments=11
[0784/1800] seed=33 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.871 deaths=1 segments=6
[0785/1800] seed=34 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.919 deaths=2 segments=7
[0786/1800] seed=35 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.915 deaths=3 segments=8
[0787/1800] seed=36 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.921 deaths=0 segments=5
[0788/1800] seed=37 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.860 deaths=4 segments=9
[0789/1800] seed=38 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.881 deaths=3 segments=8
[0790/1800] seed=39 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.864 deaths=2 segments=7
[0791/1800] seed=40 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.845 deaths=8 segments=13
[0792/1800] seed=41 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.888 deaths=2 segments=7
[0793/1800] seed=42 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.901 deaths=1 segments=6
[0794/1800] seed=43 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.811 deaths=11 segments=16
[0795/1800] seed=44 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.903 deaths=1 segments=6
[0796/1800] seed=45 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.898 deaths=2 segments=7
[0797/1800] seed=46 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.909 deaths=3 segments=8
[0798/1800] seed=47 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.918 deaths=3 segments=8
[0799/1800] seed=48 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.916 deaths=0 segments=5
[0800/1800] seed=49 decay=0.80 fill=1.30 p=0.75 smellR=14 | comfort=0.864 deaths=4 segments=9

--- checkpoint after 800 runs | elapsed 29.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0801/1800] seed=00 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.797 deaths=2 segments=7
[0802/1800] seed=01 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.866 deaths=6 segments=11
[0803/1800] seed=02 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.791 deaths=2 segments=7
[0804/1800] seed=03 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.812 deaths=3 segments=8
[0805/1800] seed=04 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.841 deaths=2 segments=7
[0806/1800] seed=05 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.826 deaths=6 segments=11
[0807/1800] seed=06 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.850 deaths=1 segments=6
[0808/1800] seed=07 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.839 deaths=0 segments=5
[0809/1800] seed=08 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.850 deaths=2 segments=7
[0810/1800] seed=09 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.829 deaths=3 segments=8
[0811/1800] seed=10 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.827 deaths=2 segments=7
[0812/1800] seed=11 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.807 deaths=2 segments=7
[0813/1800] seed=12 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.820 deaths=0 segments=5
[0814/1800] seed=13 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.799 deaths=8 segments=13
[0815/1800] seed=14 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.836 deaths=4 segments=9
[0816/1800] seed=15 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.784 deaths=6 segments=11
[0817/1800] seed=16 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.839 deaths=1 segments=6
[0818/1800] seed=17 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.832 deaths=2 segments=7
[0819/1800] seed=18 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.808 deaths=1 segments=6
[0820/1800] seed=19 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.835 deaths=1 segments=6
[0821/1800] seed=20 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.834 deaths=4 segments=9
[0822/1800] seed=21 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.840 deaths=4 segments=9
[0823/1800] seed=22 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.784 deaths=3 segments=8
[0824/1800] seed=23 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.855 deaths=0 segments=5
[0825/1800] seed=24 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.803 deaths=1 segments=6

--- checkpoint after 825 runs | elapsed 30.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50

[0826/1800] seed=25 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.882 deaths=2 segments=7
[0827/1800] seed=26 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.842 deaths=2 segments=7
[0828/1800] seed=27 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.861 deaths=1 segments=6
[0829/1800] seed=28 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.857 deaths=2 segments=7
[0830/1800] seed=29 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.844 deaths=1 segments=6
[0831/1800] seed=30 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.864 deaths=0 segments=5
[0832/1800] seed=31 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.882 deaths=1 segments=6
[0833/1800] seed=32 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.803 deaths=3 segments=8
[0834/1800] seed=33 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.790 deaths=2 segments=7
[0835/1800] seed=34 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.790 deaths=2 segments=7
[0836/1800] seed=35 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.843 deaths=2 segments=7
[0837/1800] seed=36 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.839 deaths=1 segments=6
[0838/1800] seed=37 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.812 deaths=2 segments=7
[0839/1800] seed=38 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.812 deaths=2 segments=7
[0840/1800] seed=39 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.758 deaths=5 segments=10
[0841/1800] seed=40 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.798 deaths=4 segments=9
[0842/1800] seed=41 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.835 deaths=1 segments=6
[0843/1800] seed=42 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.857 deaths=0 segments=5
[0844/1800] seed=43 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.805 deaths=3 segments=8
[0845/1800] seed=44 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.828 deaths=4 segments=9
[0846/1800] seed=45 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.821 deaths=2 segments=7
[0847/1800] seed=46 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.834 deaths=6 segments=11
[0848/1800] seed=47 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.856 deaths=0 segments=5
[0849/1800] seed=48 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.850 deaths=2 segments=7
[0850/1800] seed=49 decay=0.80 fill=1.60 p=0.55 smellR=10 | comfort=0.867 deaths=4 segments=9

--- checkpoint after 850 runs | elapsed 31.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50

[0851/1800] seed=00 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.801 deaths=3 segments=8
[0852/1800] seed=01 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.866 deaths=6 segments=11
[0853/1800] seed=02 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.791 deaths=2 segments=7
[0854/1800] seed=03 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.871 deaths=0 segments=5
[0855/1800] seed=04 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.812 deaths=3 segments=8
[0856/1800] seed=05 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.826 deaths=6 segments=11
[0857/1800] seed=06 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.849 deaths=1 segments=6
[0858/1800] seed=07 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.839 deaths=0 segments=5
[0859/1800] seed=08 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.850 deaths=2 segments=7
[0860/1800] seed=09 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.841 deaths=4 segments=9
[0861/1800] seed=10 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.827 deaths=2 segments=7
[0862/1800] seed=11 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.829 deaths=0 segments=5
[0863/1800] seed=12 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.820 deaths=0 segments=5
[0864/1800] seed=13 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.821 deaths=1 segments=6
[0865/1800] seed=14 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.836 deaths=4 segments=9
[0866/1800] seed=15 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.832 deaths=3 segments=8
[0867/1800] seed=16 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.839 deaths=1 segments=6
[0868/1800] seed=17 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.832 deaths=2 segments=7
[0869/1800] seed=18 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.808 deaths=1 segments=6
[0870/1800] seed=19 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.866 deaths=2 segments=7
[0871/1800] seed=20 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.806 deaths=3 segments=8
[0872/1800] seed=21 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.850 deaths=0 segments=5
[0873/1800] seed=22 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.784 deaths=3 segments=8
[0874/1800] seed=23 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.837 deaths=2 segments=7
[0875/1800] seed=24 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.803 deaths=1 segments=6

--- checkpoint after 875 runs | elapsed 32.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
17,0.8,1.6,0.55,14,0.829412,0.022872,2.08,2.0,6,5,7.08,11,4.0,1113.08,440.40,726.52,203.84,53.96,113.68,25
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[0876/1800] seed=25 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.843 deaths=2 segments=7
[0877/1800] seed=26 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=2 segments=7
[0878/1800] seed=27 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.857 deaths=1 segments=6
[0879/1800] seed=28 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.839 deaths=2 segments=7
[0880/1800] seed=29 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.841 deaths=1 segments=6
[0881/1800] seed=30 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.859 deaths=0 segments=5
[0882/1800] seed=31 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.805 deaths=4 segments=9
[0883/1800] seed=32 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=5 segments=10
[0884/1800] seed=33 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.790 deaths=2 segments=7
[0885/1800] seed=34 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.847 deaths=1 segments=6
[0886/1800] seed=35 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.842 deaths=2 segments=7
[0887/1800] seed=36 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.802 deaths=3 segments=8
[0888/1800] seed=37 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.806 deaths=2 segments=7
[0889/1800] seed=38 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.813 deaths=2 segments=7
[0890/1800] seed=39 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.828 deaths=1 segments=6
[0891/1800] seed=40 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.833 deaths=2 segments=7
[0892/1800] seed=41 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.835 deaths=1 segments=6
[0893/1800] seed=42 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.851 deaths=0 segments=5
[0894/1800] seed=43 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=5 segments=10
[0895/1800] seed=44 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.826 deaths=4 segments=9
[0896/1800] seed=45 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.821 deaths=2 segments=7
[0897/1800] seed=46 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.832 deaths=6 segments=11
[0898/1800] seed=47 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.856 deaths=0 segments=5
[0899/1800] seed=48 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.833 deaths=2 segments=7
[0900/1800] seed=49 decay=0.80 fill=1.60 p=0.55 smellR=14 | comfort=0.867 deaths=4 segments=9

--- checkpoint after 900 runs | elapsed 33.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[0901/1800] seed=00 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.768 deaths=7 segments=12
[0902/1800] seed=01 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.858 deaths=1 segments=6
[0903/1800] seed=02 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.803 deaths=3 segments=8
[0904/1800] seed=03 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.798 deaths=5 segments=10
[0905/1800] seed=04 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.815 deaths=3 segments=8
[0906/1800] seed=05 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.803 deaths=3 segments=8
[0907/1800] seed=06 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=1 segments=6
[0908/1800] seed=07 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.837 deaths=5 segments=10
[0909/1800] seed=08 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.820 deaths=2 segments=7
[0910/1800] seed=09 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.816 deaths=2 segments=7
[0911/1800] seed=10 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.863 deaths=1 segments=6
[0912/1800] seed=11 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.838 deaths=2 segments=7
[0913/1800] seed=12 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.809 deaths=5 segments=10
[0914/1800] seed=13 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.805 deaths=1 segments=6
[0915/1800] seed=14 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=2 segments=7
[0916/1800] seed=15 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.847 deaths=0 segments=5
[0917/1800] seed=16 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.833 deaths=2 segments=7
[0918/1800] seed=17 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=0 segments=5
[0919/1800] seed=18 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.793 deaths=4 segments=9
[0920/1800] seed=19 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.864 deaths=2 segments=7
[0921/1800] seed=20 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.795 deaths=5 segments=10
[0922/1800] seed=21 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.844 deaths=2 segments=7
[0923/1800] seed=22 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.787 deaths=5 segments=10
[0924/1800] seed=23 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=3 segments=8
[0925/1800] seed=24 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.798 deaths=1 segments=6

--- checkpoint after 925 runs | elapsed 34.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[0926/1800] seed=25 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.850 deaths=2 segments=7
[0927/1800] seed=26 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.857 deaths=3 segments=8
[0928/1800] seed=27 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.832 deaths=4 segments=9
[0929/1800] seed=28 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.829 deaths=2 segments=7
[0930/1800] seed=29 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.850 deaths=2 segments=7
[0931/1800] seed=30 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.844 deaths=1 segments=6
[0932/1800] seed=31 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.836 deaths=1 segments=6
[0933/1800] seed=32 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.761 deaths=5 segments=10
[0934/1800] seed=33 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.802 deaths=1 segments=6
[0935/1800] seed=34 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.851 deaths=2 segments=7
[0936/1800] seed=35 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.815 deaths=5 segments=10
[0937/1800] seed=36 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.838 deaths=1 segments=6
[0938/1800] seed=37 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.775 deaths=5 segments=10
[0939/1800] seed=38 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=2 segments=7
[0940/1800] seed=39 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=3 segments=8
[0941/1800] seed=40 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.767 deaths=8 segments=13
[0942/1800] seed=41 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.820 deaths=7 segments=12
[0943/1800] seed=42 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.807 deaths=1 segments=6
[0944/1800] seed=43 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.736 deaths=12 segments=17
[0945/1800] seed=44 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.775 deaths=3 segments=8
[0946/1800] seed=45 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.837 deaths=2 segments=7
[0947/1800] seed=46 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.787 deaths=2 segments=7
[0948/1800] seed=47 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.847 deaths=4 segments=9
[0949/1800] seed=48 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.847 deaths=0 segments=5
[0950/1800] seed=49 decay=0.80 fill=1.60 p=0.75 smellR=10 | comfort=0.795 deaths=5 segments=10

--- checkpoint after 950 runs | elapsed 35.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[0951/1800] seed=00 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.801 deaths=4 segments=9
[0952/1800] seed=01 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.877 deaths=0 segments=5
[0953/1800] seed=02 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.844 deaths=3 segments=8
[0954/1800] seed=03 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.803 deaths=3 segments=8
[0955/1800] seed=04 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.815 deaths=3 segments=8
[0956/1800] seed=05 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.807 deaths=6 segments=11
[0957/1800] seed=06 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.844 deaths=2 segments=7
[0958/1800] seed=07 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.838 deaths=2 segments=7
[0959/1800] seed=08 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.821 deaths=2 segments=7
[0960/1800] seed=09 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.801 deaths=4 segments=9
[0961/1800] seed=10 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.863 deaths=1 segments=6
[0962/1800] seed=11 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.820 deaths=5 segments=10
[0963/1800] seed=12 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.840 deaths=2 segments=7
[0964/1800] seed=13 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.805 deaths=1 segments=6
[0965/1800] seed=14 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.823 deaths=2 segments=7
[0966/1800] seed=15 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.799 deaths=6 segments=11
[0967/1800] seed=16 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.833 deaths=2 segments=7
[0968/1800] seed=17 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.838 deaths=0 segments=5
[0969/1800] seed=18 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.793 deaths=4 segments=9
[0970/1800] seed=19 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.797 deaths=3 segments=8
[0971/1800] seed=20 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.795 deaths=5 segments=10
[0972/1800] seed=21 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.834 deaths=3 segments=8
[0973/1800] seed=22 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.787 deaths=5 segments=10
[0974/1800] seed=23 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.828 deaths=3 segments=8
[0975/1800] seed=24 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=1 segments=6

--- checkpoint after 975 runs | elapsed 36.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[0976/1800] seed=25 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.850 deaths=2 segments=7
[0977/1800] seed=26 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=2 segments=7
[0978/1800] seed=27 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.827 deaths=5 segments=10
[0979/1800] seed=28 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.846 deaths=5 segments=10
[0980/1800] seed=29 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.817 deaths=5 segments=10
[0981/1800] seed=30 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.846 deaths=1 segments=6
[0982/1800] seed=31 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.824 deaths=2 segments=7
[0983/1800] seed=32 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.761 deaths=5 segments=10
[0984/1800] seed=33 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.802 deaths=1 segments=6
[0985/1800] seed=34 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.851 deaths=2 segments=7
[0986/1800] seed=35 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.812 deaths=1 segments=6
[0987/1800] seed=36 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.839 deaths=0 segments=5
[0988/1800] seed=37 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.776 deaths=4 segments=9
[0989/1800] seed=38 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.833 deaths=3 segments=8
[0990/1800] seed=39 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.807 deaths=2 segments=7
[0991/1800] seed=40 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.766 deaths=8 segments=13
[0992/1800] seed=41 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.853 deaths=4 segments=9
[0993/1800] seed=42 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.807 deaths=1 segments=6
[0994/1800] seed=43 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.736 deaths=12 segments=17
[0995/1800] seed=44 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.770 deaths=5 segments=10
[0996/1800] seed=45 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.836 deaths=2 segments=7
[0997/1800] seed=46 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.792 deaths=5 segments=10
[0998/1800] seed=47 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.814 deaths=2 segments=7
[0999/1800] seed=48 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.847 deaths=0 segments=5
[1000/1800] seed=49 decay=0.80 fill=1.60 p=0.75 smellR=14 | comfort=0.825 deaths=3 segments=8

--- checkpoint after 1000 runs | elapsed 37.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50

[1001/1800] seed=00 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.724 deaths=2 segments=7
[1002/1800] seed=01 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.733 deaths=4 segments=9
[1003/1800] seed=02 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.734 deaths=3 segments=8
[1004/1800] seed=03 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.731 deaths=3 segments=8
[1005/1800] seed=04 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=2 segments=7
[1006/1800] seed=05 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=2 segments=7
[1007/1800] seed=06 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.759 deaths=1 segments=6
[1008/1800] seed=07 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.758 deaths=0 segments=5
[1009/1800] seed=08 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.766 deaths=2 segments=7
[1010/1800] seed=09 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.726 deaths=0 segments=5
[1011/1800] seed=10 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.746 deaths=1 segments=6
[1012/1800] seed=11 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.752 deaths=1 segments=6
[1013/1800] seed=12 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.726 deaths=0 segments=5
[1014/1800] seed=13 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.746 deaths=1 segments=6
[1015/1800] seed=14 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.735 deaths=3 segments=8
[1016/1800] seed=15 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.696 deaths=6 segments=11
[1017/1800] seed=16 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.744 deaths=1 segments=6
[1018/1800] seed=17 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.733 deaths=4 segments=9
[1019/1800] seed=18 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=1 segments=6
[1020/1800] seed=19 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.761 deaths=1 segments=6
[1021/1800] seed=20 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.724 deaths=3 segments=8
[1022/1800] seed=21 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.756 deaths=4 segments=9
[1023/1800] seed=22 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.744 deaths=3 segments=8
[1024/1800] seed=23 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.751 deaths=0 segments=5
[1025/1800] seed=24 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.733 deaths=1 segments=6

--- checkpoint after 1025 runs | elapsed 38.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
20,0.8,1.9,0.55,10,0.739791,0.015213,1.96,2.0,6,4,6.96,11,4.0,1037.04,487.28,751.68,199.96,53.40,121.36,25
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50

[1026/1800] seed=25 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.772 deaths=2 segments=7
[1027/1800] seed=26 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.762 deaths=2 segments=7
[1028/1800] seed=27 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.779 deaths=1 segments=6
[1029/1800] seed=28 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.761 deaths=2 segments=7
[1030/1800] seed=29 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.751 deaths=1 segments=6
[1031/1800] seed=30 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.717 deaths=6 segments=11
[1032/1800] seed=31 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.775 deaths=1 segments=6
[1033/1800] seed=32 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.750 deaths=0 segments=5
[1034/1800] seed=33 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.714 deaths=2 segments=7
[1035/1800] seed=34 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.721 deaths=2 segments=7
[1036/1800] seed=35 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.768 deaths=0 segments=5
[1037/1800] seed=36 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.747 deaths=1 segments=6
[1038/1800] seed=37 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.716 deaths=2 segments=7
[1039/1800] seed=38 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.708 deaths=3 segments=8
[1040/1800] seed=39 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.694 deaths=5 segments=10
[1041/1800] seed=40 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.730 deaths=4 segments=9
[1042/1800] seed=41 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.744 deaths=1 segments=6
[1043/1800] seed=42 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.757 deaths=0 segments=5
[1044/1800] seed=43 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.732 deaths=4 segments=9
[1045/1800] seed=44 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.736 deaths=5 segments=10
[1046/1800] seed=45 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.720 deaths=2 segments=7
[1047/1800] seed=46 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.753 deaths=6 segments=11
[1048/1800] seed=47 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.760 deaths=0 segments=5
[1049/1800] seed=48 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.741 deaths=2 segments=7
[1050/1800] seed=49 decay=0.80 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=2 segments=7

--- checkpoint after 1050 runs | elapsed 39.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50

[1051/1800] seed=00 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.730 deaths=3 segments=8
[1052/1800] seed=01 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=8 segments=13
[1053/1800] seed=02 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.751 deaths=3 segments=8
[1054/1800] seed=03 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.768 deaths=3 segments=8
[1055/1800] seed=04 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.740 deaths=2 segments=7
[1056/1800] seed=05 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.740 deaths=2 segments=7
[1057/1800] seed=06 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.757 deaths=1 segments=6
[1058/1800] seed=07 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.758 deaths=0 segments=5
[1059/1800] seed=08 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.766 deaths=2 segments=7
[1060/1800] seed=09 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.726 deaths=0 segments=5
[1061/1800] seed=10 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=1 segments=6
[1062/1800] seed=11 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.752 deaths=1 segments=6
[1063/1800] seed=12 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.726 deaths=0 segments=5
[1064/1800] seed=13 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=1 segments=6
[1065/1800] seed=14 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.735 deaths=3 segments=8
[1066/1800] seed=15 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=3 segments=8
[1067/1800] seed=16 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.744 deaths=1 segments=6
[1068/1800] seed=17 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.743 deaths=4 segments=9
[1069/1800] seed=18 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.738 deaths=1 segments=6
[1070/1800] seed=19 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.775 deaths=2 segments=7
[1071/1800] seed=20 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.724 deaths=3 segments=8
[1072/1800] seed=21 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.736 deaths=2 segments=7
[1073/1800] seed=22 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.744 deaths=3 segments=8
[1074/1800] seed=23 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.745 deaths=2 segments=7
[1075/1800] seed=24 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.733 deaths=1 segments=6

--- checkpoint after 1075 runs | elapsed 40.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.744919,0.013151,2.08,2.0,8,3,7.08,13,4.0,1028.12,492.40,731.76,199.88,53.64,114.96,25
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1076/1800] seed=25 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.761 deaths=2 segments=7
[1077/1800] seed=26 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=2 segments=7
[1078/1800] seed=27 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.760 deaths=1 segments=6
[1079/1800] seed=28 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.760 deaths=2 segments=7
[1080/1800] seed=29 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.752 deaths=1 segments=6
[1081/1800] seed=30 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.695 deaths=5 segments=10
[1082/1800] seed=31 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.722 deaths=4 segments=9
[1083/1800] seed=32 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.750 deaths=0 segments=5
[1084/1800] seed=33 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.714 deaths=2 segments=7
[1085/1800] seed=34 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.726 deaths=1 segments=6
[1086/1800] seed=35 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.768 deaths=0 segments=5
[1087/1800] seed=36 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.733 deaths=3 segments=8
[1088/1800] seed=37 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.710 deaths=2 segments=7
[1089/1800] seed=38 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.735 deaths=2 segments=7
[1090/1800] seed=39 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.734 deaths=1 segments=6
[1091/1800] seed=40 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.746 deaths=2 segments=7
[1092/1800] seed=41 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.744 deaths=1 segments=6
[1093/1800] seed=42 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.752 deaths=0 segments=5
[1094/1800] seed=43 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.732 deaths=6 segments=11
[1095/1800] seed=44 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.706 deaths=2 segments=7
[1096/1800] seed=45 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.720 deaths=2 segments=7
[1097/1800] seed=46 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.751 deaths=6 segments=11
[1098/1800] seed=47 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.760 deaths=0 segments=5
[1099/1800] seed=48 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.741 deaths=2 segments=7
[1100/1800] seed=49 decay=0.80 fill=1.90 p=0.55 smellR=14 | comfort=0.745 deaths=3 segments=8

--- checkpoint after 1100 runs | elapsed 41.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1101/1800] seed=00 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.693 deaths=4 segments=9
[1102/1800] seed=01 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.748 deaths=0 segments=5
[1103/1800] seed=02 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.733 deaths=3 segments=8
[1104/1800] seed=03 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.737 deaths=3 segments=8
[1105/1800] seed=04 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.758 deaths=1 segments=6
[1106/1800] seed=05 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.739 deaths=3 segments=8
[1107/1800] seed=06 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.743 deaths=1 segments=6
[1108/1800] seed=07 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.765 deaths=4 segments=9
[1109/1800] seed=08 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=2 segments=7
[1110/1800] seed=09 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.746 deaths=2 segments=7
[1111/1800] seed=10 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=2 segments=7
[1112/1800] seed=11 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.706 deaths=4 segments=9
[1113/1800] seed=12 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.727 deaths=5 segments=10
[1114/1800] seed=13 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=4 segments=9
[1115/1800] seed=14 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.728 deaths=2 segments=7
[1116/1800] seed=15 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.690 deaths=9 segments=14
[1117/1800] seed=16 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.755 deaths=2 segments=7
[1118/1800] seed=17 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.740 deaths=0 segments=5
[1119/1800] seed=18 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.694 deaths=6 segments=11
[1120/1800] seed=19 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=2 segments=7
[1121/1800] seed=20 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.728 deaths=1 segments=6
[1122/1800] seed=21 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.714 deaths=0 segments=5
[1123/1800] seed=22 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.694 deaths=5 segments=10
[1124/1800] seed=23 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.739 deaths=3 segments=8
[1125/1800] seed=24 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.724 deaths=1 segments=6

--- checkpoint after 1125 runs | elapsed 41.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1126/1800] seed=25 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.738 deaths=2 segments=7
[1127/1800] seed=26 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.776 deaths=3 segments=8
[1128/1800] seed=27 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.758 deaths=3 segments=8
[1129/1800] seed=28 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.706 deaths=6 segments=11
[1130/1800] seed=29 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.747 deaths=2 segments=7
[1131/1800] seed=30 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.758 deaths=1 segments=6
[1132/1800] seed=31 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.727 deaths=4 segments=9
[1133/1800] seed=32 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=5 segments=10
[1134/1800] seed=33 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.731 deaths=1 segments=6
[1135/1800] seed=34 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.750 deaths=2 segments=7
[1136/1800] seed=35 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.719 deaths=3 segments=8
[1137/1800] seed=36 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.721 deaths=5 segments=10
[1138/1800] seed=37 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.699 deaths=5 segments=10
[1139/1800] seed=38 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.760 deaths=3 segments=8
[1140/1800] seed=39 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.731 deaths=3 segments=8
[1141/1800] seed=40 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=7 segments=12
[1142/1800] seed=41 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.684 deaths=6 segments=11
[1143/1800] seed=42 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.715 deaths=1 segments=6
[1144/1800] seed=43 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.685 deaths=10 segments=15
[1145/1800] seed=44 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.744 deaths=4 segments=9
[1146/1800] seed=45 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.749 deaths=2 segments=7
[1147/1800] seed=46 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.751 deaths=2 segments=7
[1148/1800] seed=47 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.741 deaths=1 segments=6
[1149/1800] seed=48 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.750 deaths=0 segments=5
[1150/1800] seed=49 decay=0.80 fill=1.90 p=0.75 smellR=10 | comfort=0.719 deaths=3 segments=8

--- checkpoint after 1150 runs | elapsed 42.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1151/1800] seed=00 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.748 deaths=3 segments=8
[1152/1800] seed=01 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.748 deaths=0 segments=5
[1153/1800] seed=02 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.751 deaths=3 segments=8
[1154/1800] seed=03 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.734 deaths=3 segments=8
[1155/1800] seed=04 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.758 deaths=1 segments=6
[1156/1800] seed=05 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.739 deaths=3 segments=8
[1157/1800] seed=06 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.745 deaths=2 segments=7
[1158/1800] seed=07 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.729 deaths=4 segments=9
[1159/1800] seed=08 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.736 deaths=2 segments=7
[1160/1800] seed=09 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=4 segments=9
[1161/1800] seed=10 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.736 deaths=1 segments=6
[1162/1800] seed=11 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.722 deaths=5 segments=10
[1163/1800] seed=12 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.721 deaths=2 segments=7
[1164/1800] seed=13 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.703 deaths=4 segments=9
[1165/1800] seed=14 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.728 deaths=2 segments=7
[1166/1800] seed=15 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.706 deaths=6 segments=11
[1167/1800] seed=16 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.755 deaths=2 segments=7
[1168/1800] seed=17 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.729 deaths=0 segments=5
[1169/1800] seed=18 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.701 deaths=6 segments=11
[1170/1800] seed=19 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.721 deaths=3 segments=8
[1171/1800] seed=20 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.748 deaths=1 segments=6
[1172/1800] seed=21 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.746 deaths=2 segments=7
[1173/1800] seed=22 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.694 deaths=5 segments=10
[1174/1800] seed=23 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.719 deaths=2 segments=7
[1175/1800] seed=24 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.741 deaths=1 segments=6

--- checkpoint after 1175 runs | elapsed 43.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1176/1800] seed=25 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.738 deaths=2 segments=7
[1177/1800] seed=26 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=3 segments=8
[1178/1800] seed=27 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=3 segments=8
[1179/1800] seed=28 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.706 deaths=6 segments=11
[1180/1800] seed=29 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.726 deaths=1 segments=6
[1181/1800] seed=30 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.758 deaths=1 segments=6
[1182/1800] seed=31 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.741 deaths=2 segments=7
[1183/1800] seed=32 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.703 deaths=5 segments=10
[1184/1800] seed=33 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=1 segments=6
[1185/1800] seed=34 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.750 deaths=2 segments=7
[1186/1800] seed=35 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=2 segments=7
[1187/1800] seed=36 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.756 deaths=0 segments=5
[1188/1800] seed=37 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.700 deaths=4 segments=9
[1189/1800] seed=38 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.696 deaths=10 segments=15
[1190/1800] seed=39 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.738 deaths=2 segments=7
[1191/1800] seed=40 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.703 deaths=7 segments=12
[1192/1800] seed=41 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.684 deaths=6 segments=11
[1193/1800] seed=42 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.715 deaths=1 segments=6
[1194/1800] seed=43 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.685 deaths=11 segments=16
[1195/1800] seed=44 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.733 deaths=3 segments=8
[1196/1800] seed=45 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=2 segments=7
[1197/1800] seed=46 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.722 deaths=1 segments=6
[1198/1800] seed=47 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.747 deaths=3 segments=8
[1199/1800] seed=48 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.750 deaths=0 segments=5
[1200/1800] seed=49 decay=0.80 fill=1.90 p=0.75 smellR=14 | comfort=0.719 deaths=3 segments=8

--- checkpoint after 1200 runs | elapsed 44.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1201/1800] seed=00 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.881 deaths=1 segments=6
[1202/1800] seed=01 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.869 deaths=7 segments=12
[1203/1800] seed=02 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.896 deaths=1 segments=6
[1204/1800] seed=03 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.889 deaths=1 segments=6
[1205/1800] seed=04 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.903 deaths=2 segments=7
[1206/1800] seed=05 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.877 deaths=4 segments=9
[1207/1800] seed=06 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.895 deaths=3 segments=8
[1208/1800] seed=07 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.914 deaths=2 segments=7
[1209/1800] seed=08 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.882 deaths=4 segments=9
[1210/1800] seed=09 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.921 deaths=0 segments=5
[1211/1800] seed=10 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.899 deaths=1 segments=6
[1212/1800] seed=11 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.893 deaths=3 segments=8
[1213/1800] seed=12 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.864 deaths=3 segments=8
[1214/1800] seed=13 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.893 deaths=7 segments=12
[1215/1800] seed=14 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.915 deaths=0 segments=5
[1216/1800] seed=15 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.875 deaths=1 segments=6
[1217/1800] seed=16 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.885 deaths=1 segments=6
[1218/1800] seed=17 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.891 deaths=3 segments=8
[1219/1800] seed=18 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.916 deaths=1 segments=6
[1220/1800] seed=19 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.852 deaths=6 segments=11
[1221/1800] seed=20 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.906 deaths=2 segments=7
[1222/1800] seed=21 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.883 deaths=3 segments=8
[1223/1800] seed=22 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.892 deaths=2 segments=7
[1224/1800] seed=23 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.918 deaths=6 segments=11
[1225/1800] seed=24 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.852 deaths=3 segments=8

--- checkpoint after 1225 runs | elapsed 45.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1226/1800] seed=25 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.887 deaths=4 segments=9
[1227/1800] seed=26 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.876 deaths=2 segments=7
[1228/1800] seed=27 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.893 deaths=2 segments=7
[1229/1800] seed=28 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.911 deaths=2 segments=7
[1230/1800] seed=29 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.908 deaths=0 segments=5
[1231/1800] seed=30 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.902 deaths=0 segments=5
[1232/1800] seed=31 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.877 deaths=4 segments=9
[1233/1800] seed=32 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.888 deaths=3 segments=8
[1234/1800] seed=33 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.919 deaths=2 segments=7
[1235/1800] seed=34 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.905 deaths=2 segments=7
[1236/1800] seed=35 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.900 deaths=5 segments=10
[1237/1800] seed=36 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.880 deaths=0 segments=5
[1238/1800] seed=37 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.906 deaths=3 segments=8
[1239/1800] seed=38 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.881 deaths=2 segments=7
[1240/1800] seed=39 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.896 deaths=4 segments=9
[1241/1800] seed=40 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.897 deaths=5 segments=10
[1242/1800] seed=41 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.868 deaths=2 segments=7
[1243/1800] seed=42 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.888 deaths=4 segments=9
[1244/1800] seed=43 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.919 deaths=1 segments=6
[1245/1800] seed=44 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.880 deaths=7 segments=12
[1246/1800] seed=45 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.913 deaths=2 segments=7
[1247/1800] seed=46 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.912 deaths=0 segments=5
[1248/1800] seed=47 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.903 deaths=1 segments=6
[1249/1800] seed=48 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.900 deaths=2 segments=7
[1250/1800] seed=49 decay=0.90 fill=1.30 p=0.55 smellR=10 | comfort=0.870 deaths=5 segments=10

--- checkpoint after 1250 runs | elapsed 46.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1251/1800] seed=00 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.897 deaths=1 segments=6
[1252/1800] seed=01 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.867 deaths=7 segments=12
[1253/1800] seed=02 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.903 deaths=1 segments=6
[1254/1800] seed=03 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.906 deaths=2 segments=7
[1255/1800] seed=04 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.880 deaths=2 segments=7
[1256/1800] seed=05 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.877 deaths=4 segments=9
[1257/1800] seed=06 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.901 deaths=3 segments=8
[1258/1800] seed=07 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.914 deaths=2 segments=7
[1259/1800] seed=08 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.882 deaths=4 segments=9
[1260/1800] seed=09 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.921 deaths=0 segments=5
[1261/1800] seed=10 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=2 segments=7
[1262/1800] seed=11 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=3 segments=8
[1263/1800] seed=12 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.864 deaths=3 segments=8
[1264/1800] seed=13 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.911 deaths=4 segments=9
[1265/1800] seed=14 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.915 deaths=0 segments=5
[1266/1800] seed=15 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.920 deaths=1 segments=6
[1267/1800] seed=16 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.888 deaths=2 segments=7
[1268/1800] seed=17 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.900 deaths=3 segments=8
[1269/1800] seed=18 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.916 deaths=1 segments=6
[1270/1800] seed=19 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.888 deaths=2 segments=7
[1271/1800] seed=20 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.906 deaths=2 segments=7
[1272/1800] seed=21 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=5 segments=10
[1273/1800] seed=22 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.884 deaths=1 segments=6
[1274/1800] seed=23 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.887 deaths=2 segments=7
[1275/1800] seed=24 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.872 deaths=1 segments=6

--- checkpoint after 1275 runs | elapsed 47.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1276/1800] seed=25 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.895 deaths=1 segments=6
[1277/1800] seed=26 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.918 deaths=4 segments=9
[1278/1800] seed=27 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.893 deaths=2 segments=7
[1279/1800] seed=28 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.915 deaths=2 segments=7
[1280/1800] seed=29 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.902 deaths=2 segments=7
[1281/1800] seed=30 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.907 deaths=2 segments=7
[1282/1800] seed=31 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.868 deaths=4 segments=9
[1283/1800] seed=32 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.905 deaths=1 segments=6
[1284/1800] seed=33 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.919 deaths=2 segments=7
[1285/1800] seed=34 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.879 deaths=2 segments=7
[1286/1800] seed=35 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.900 deaths=5 segments=10
[1287/1800] seed=36 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.936 deaths=1 segments=6
[1288/1800] seed=37 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.906 deaths=3 segments=8
[1289/1800] seed=38 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.881 deaths=2 segments=7
[1290/1800] seed=39 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.885 deaths=3 segments=8
[1291/1800] seed=40 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.896 deaths=5 segments=10
[1292/1800] seed=41 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.868 deaths=2 segments=7
[1293/1800] seed=42 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.888 deaths=4 segments=9
[1294/1800] seed=43 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.919 deaths=1 segments=6
[1295/1800] seed=44 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.864 deaths=7 segments=12
[1296/1800] seed=45 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.913 deaths=2 segments=7
[1297/1800] seed=46 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.912 deaths=0 segments=5
[1298/1800] seed=47 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.894 deaths=2 segments=7
[1299/1800] seed=48 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.900 deaths=2 segments=7
[1300/1800] seed=49 decay=0.90 fill=1.30 p=0.55 smellR=14 | comfort=0.910 deaths=2 segments=7

--- checkpoint after 1300 runs | elapsed 48.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1301/1800] seed=00 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.903 deaths=3 segments=8
[1302/1800] seed=01 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.862 deaths=10 segments=15
[1303/1800] seed=02 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=4 segments=9
[1304/1800] seed=03 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.895 deaths=1 segments=6
[1305/1800] seed=04 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.877 deaths=5 segments=10
[1306/1800] seed=05 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.882 deaths=2 segments=7
[1307/1800] seed=06 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=3 segments=8
[1308/1800] seed=07 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.840 deaths=8 segments=13
[1309/1800] seed=08 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.900 deaths=3 segments=8
[1310/1800] seed=09 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.901 deaths=0 segments=5
[1311/1800] seed=10 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.908 deaths=3 segments=8
[1312/1800] seed=11 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.868 deaths=4 segments=9
[1313/1800] seed=12 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.894 deaths=3 segments=8
[1314/1800] seed=13 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.906 deaths=6 segments=11
[1315/1800] seed=14 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.904 deaths=3 segments=8
[1316/1800] seed=15 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.895 deaths=2 segments=7
[1317/1800] seed=16 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.870 deaths=6 segments=11
[1318/1800] seed=17 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.870 deaths=3 segments=8
[1319/1800] seed=18 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.910 deaths=1 segments=6
[1320/1800] seed=19 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.905 deaths=1 segments=6
[1321/1800] seed=20 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.877 deaths=5 segments=10
[1322/1800] seed=21 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.881 deaths=1 segments=6
[1323/1800] seed=22 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.917 deaths=5 segments=10
[1324/1800] seed=23 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.877 deaths=2 segments=7
[1325/1800] seed=24 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.897 deaths=5 segments=10

--- checkpoint after 1325 runs | elapsed 49.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1326/1800] seed=25 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.893 deaths=3 segments=8
[1327/1800] seed=26 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.880 deaths=8 segments=13
[1328/1800] seed=27 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.898 deaths=1 segments=6
[1329/1800] seed=28 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.912 deaths=2 segments=7
[1330/1800] seed=29 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.907 deaths=3 segments=8
[1331/1800] seed=30 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.860 deaths=2 segments=7
[1332/1800] seed=31 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.891 deaths=5 segments=10
[1333/1800] seed=32 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.856 deaths=4 segments=9
[1334/1800] seed=33 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.886 deaths=6 segments=11
[1335/1800] seed=34 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.891 deaths=2 segments=7
[1336/1800] seed=35 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.861 deaths=9 segments=14
[1337/1800] seed=36 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.922 deaths=2 segments=7
[1338/1800] seed=37 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.858 deaths=8 segments=13
[1339/1800] seed=38 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.833 deaths=3 segments=8
[1340/1800] seed=39 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.854 deaths=4 segments=9
[1341/1800] seed=40 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.880 deaths=4 segments=9
[1342/1800] seed=41 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.881 deaths=7 segments=12
[1343/1800] seed=42 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.884 deaths=5 segments=10
[1344/1800] seed=43 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.859 deaths=8 segments=13
[1345/1800] seed=44 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.884 deaths=5 segments=10
[1346/1800] seed=45 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.888 deaths=3 segments=8
[1347/1800] seed=46 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.883 deaths=0 segments=5
[1348/1800] seed=47 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.875 deaths=3 segments=8
[1349/1800] seed=48 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.906 deaths=3 segments=8
[1350/1800] seed=49 decay=0.90 fill=1.30 p=0.75 smellR=10 | comfort=0.920 deaths=2 segments=7

--- checkpoint after 1350 runs | elapsed 50.5 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1351/1800] seed=00 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.903 deaths=3 segments=8
[1352/1800] seed=01 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.893 deaths=3 segments=8
[1353/1800] seed=02 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.901 deaths=4 segments=9
[1354/1800] seed=03 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.879 deaths=5 segments=10
[1355/1800] seed=04 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.877 deaths=5 segments=10
[1356/1800] seed=05 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.882 deaths=2 segments=7
[1357/1800] seed=06 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.901 deaths=3 segments=8
[1358/1800] seed=07 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.883 deaths=5 segments=10
[1359/1800] seed=08 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.900 deaths=3 segments=8
[1360/1800] seed=09 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.913 deaths=0 segments=5
[1361/1800] seed=10 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.872 deaths=3 segments=8
[1362/1800] seed=11 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.846 deaths=7 segments=12
[1363/1800] seed=12 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.888 deaths=4 segments=9
[1364/1800] seed=13 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.906 deaths=6 segments=11
[1365/1800] seed=14 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.915 deaths=0 segments=5
[1366/1800] seed=15 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.884 deaths=3 segments=8
[1367/1800] seed=16 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.853 deaths=4 segments=9
[1368/1800] seed=17 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.868 deaths=3 segments=8
[1369/1800] seed=18 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.910 deaths=1 segments=6
[1370/1800] seed=19 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.905 deaths=1 segments=6
[1371/1800] seed=20 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.895 deaths=5 segments=10
[1372/1800] seed=21 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.832 deaths=8 segments=13
[1373/1800] seed=22 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.917 deaths=5 segments=10
[1374/1800] seed=23 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.899 deaths=2 segments=7
[1375/1800] seed=24 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.898 deaths=4 segments=9

--- checkpoint after 1375 runs | elapsed 51.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1376/1800] seed=25 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.896 deaths=4 segments=9
[1377/1800] seed=26 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.865 deaths=2 segments=7
[1378/1800] seed=27 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.895 deaths=1 segments=6
[1379/1800] seed=28 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.912 deaths=2 segments=7
[1380/1800] seed=29 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.898 deaths=4 segments=9
[1381/1800] seed=30 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.898 deaths=2 segments=7
[1382/1800] seed=31 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.891 deaths=5 segments=10
[1383/1800] seed=32 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.856 deaths=4 segments=9
[1384/1800] seed=33 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.886 deaths=6 segments=11
[1385/1800] seed=34 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.889 deaths=2 segments=7
[1386/1800] seed=35 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.861 deaths=9 segments=14
[1387/1800] seed=36 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.901 deaths=2 segments=7
[1388/1800] seed=37 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.895 deaths=1 segments=6
[1389/1800] seed=38 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.859 deaths=4 segments=9
[1390/1800] seed=39 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.854 deaths=4 segments=9
[1391/1800] seed=40 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.876 deaths=2 segments=7
[1392/1800] seed=41 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.882 deaths=7 segments=12
[1393/1800] seed=42 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.864 deaths=7 segments=12
[1394/1800] seed=43 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.849 deaths=8 segments=13
[1395/1800] seed=44 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.895 deaths=5 segments=10
[1396/1800] seed=45 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.888 deaths=3 segments=8
[1397/1800] seed=46 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.883 deaths=0 segments=5
[1398/1800] seed=47 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.874 deaths=5 segments=10
[1399/1800] seed=48 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.906 deaths=3 segments=8
[1400/1800] seed=49 decay=0.90 fill=1.30 p=0.75 smellR=14 | comfort=0.916 deaths=2 segments=7

--- checkpoint after 1400 runs | elapsed 52.4 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1401/1800] seed=00 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.832 deaths=1 segments=6
[1402/1800] seed=01 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.831 deaths=1 segments=6
[1403/1800] seed=02 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.827 deaths=1 segments=6
[1404/1800] seed=03 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.830 deaths=1 segments=6
[1405/1800] seed=04 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.803 deaths=2 segments=7
[1406/1800] seed=05 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.867 deaths=2 segments=7
[1407/1800] seed=06 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.853 deaths=3 segments=8
[1408/1800] seed=07 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.849 deaths=4 segments=9
[1409/1800] seed=08 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.813 deaths=4 segments=9
[1410/1800] seed=09 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.838 deaths=3 segments=8
[1411/1800] seed=10 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.861 deaths=1 segments=6
[1412/1800] seed=11 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.813 deaths=3 segments=8
[1413/1800] seed=12 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.807 deaths=5 segments=10
[1414/1800] seed=13 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.781 deaths=4 segments=9
[1415/1800] seed=14 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.829 deaths=0 segments=5
[1416/1800] seed=15 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.817 deaths=1 segments=6
[1417/1800] seed=16 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.845 deaths=2 segments=7
[1418/1800] seed=17 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.825 deaths=2 segments=7
[1419/1800] seed=18 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.875 deaths=1 segments=6
[1420/1800] seed=19 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.802 deaths=6 segments=11
[1421/1800] seed=20 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.814 deaths=5 segments=10
[1422/1800] seed=21 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.842 deaths=3 segments=8
[1423/1800] seed=22 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.826 deaths=2 segments=7
[1424/1800] seed=23 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.848 deaths=6 segments=11
[1425/1800] seed=24 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=2 segments=7

--- checkpoint after 1425 runs | elapsed 53.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1426/1800] seed=25 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.860 deaths=1 segments=6
[1427/1800] seed=26 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.844 deaths=3 segments=8
[1428/1800] seed=27 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.839 deaths=2 segments=7
[1429/1800] seed=28 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.888 deaths=3 segments=8
[1430/1800] seed=29 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.862 deaths=0 segments=5
[1431/1800] seed=30 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=1 segments=6
[1432/1800] seed=31 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.822 deaths=4 segments=9
[1433/1800] seed=32 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.831 deaths=3 segments=8
[1434/1800] seed=33 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.841 deaths=0 segments=5
[1435/1800] seed=34 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.846 deaths=2 segments=7
[1436/1800] seed=35 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.843 deaths=3 segments=8
[1437/1800] seed=36 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.829 deaths=0 segments=5
[1438/1800] seed=37 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.820 deaths=4 segments=9
[1439/1800] seed=38 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.826 deaths=1 segments=6
[1440/1800] seed=39 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.848 deaths=1 segments=6
[1441/1800] seed=40 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.848 deaths=4 segments=9
[1442/1800] seed=41 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.861 deaths=1 segments=6
[1443/1800] seed=42 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.836 deaths=4 segments=9
[1444/1800] seed=43 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.880 deaths=1 segments=6
[1445/1800] seed=44 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.847 deaths=3 segments=8
[1446/1800] seed=45 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.844 deaths=2 segments=7
[1447/1800] seed=46 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.846 deaths=0 segments=5
[1448/1800] seed=47 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.865 deaths=1 segments=6
[1449/1800] seed=48 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.851 deaths=4 segments=9
[1450/1800] seed=49 decay=0.90 fill=1.60 p=0.55 smellR=10 | comfort=0.815 deaths=4 segments=9

--- checkpoint after 1450 runs | elapsed 54.3 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1451/1800] seed=00 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.828 deaths=1 segments=6
[1452/1800] seed=01 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.812 deaths=2 segments=7
[1453/1800] seed=02 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.831 deaths=2 segments=7
[1454/1800] seed=03 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.845 deaths=2 segments=7
[1455/1800] seed=04 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.803 deaths=2 segments=7
[1456/1800] seed=05 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.867 deaths=2 segments=7
[1457/1800] seed=06 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.852 deaths=3 segments=8
[1458/1800] seed=07 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.849 deaths=4 segments=9
[1459/1800] seed=08 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.813 deaths=4 segments=9
[1460/1800] seed=09 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.833 deaths=3 segments=8
[1461/1800] seed=10 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.860 deaths=1 segments=6
[1462/1800] seed=11 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.813 deaths=3 segments=8
[1463/1800] seed=12 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.786 deaths=5 segments=10
[1464/1800] seed=13 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.781 deaths=4 segments=9
[1465/1800] seed=14 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.829 deaths=0 segments=5
[1466/1800] seed=15 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.831 deaths=4 segments=9
[1467/1800] seed=16 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.845 deaths=2 segments=7
[1468/1800] seed=17 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.842 deaths=3 segments=8
[1469/1800] seed=18 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.875 deaths=1 segments=6
[1470/1800] seed=19 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.838 deaths=3 segments=8
[1471/1800] seed=20 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.814 deaths=5 segments=10
[1472/1800] seed=21 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.805 deaths=3 segments=8
[1473/1800] seed=22 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.834 deaths=1 segments=6
[1474/1800] seed=23 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.779 deaths=6 segments=11
[1475/1800] seed=24 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.825 deaths=1 segments=6

--- checkpoint after 1475 runs | elapsed 55.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1476/1800] seed=25 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.860 deaths=1 segments=6
[1477/1800] seed=26 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.842 deaths=3 segments=8
[1478/1800] seed=27 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.839 deaths=2 segments=7
[1479/1800] seed=28 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.779 deaths=2 segments=7
[1480/1800] seed=29 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.862 deaths=0 segments=5
[1481/1800] seed=30 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.822 deaths=1 segments=6
[1482/1800] seed=31 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.856 deaths=2 segments=7
[1483/1800] seed=32 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.840 deaths=2 segments=7
[1484/1800] seed=33 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.841 deaths=0 segments=5
[1485/1800] seed=34 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.816 deaths=2 segments=7
[1486/1800] seed=35 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.843 deaths=3 segments=8
[1487/1800] seed=36 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.848 deaths=2 segments=7
[1488/1800] seed=37 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.815 deaths=4 segments=9
[1489/1800] seed=38 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.826 deaths=1 segments=6
[1490/1800] seed=39 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.869 deaths=4 segments=9
[1491/1800] seed=40 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.848 deaths=4 segments=9
[1492/1800] seed=41 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.861 deaths=1 segments=6
[1493/1800] seed=42 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.836 deaths=4 segments=9
[1494/1800] seed=43 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.880 deaths=1 segments=6
[1495/1800] seed=44 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.832 deaths=4 segments=9
[1496/1800] seed=45 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.844 deaths=2 segments=7
[1497/1800] seed=46 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.846 deaths=0 segments=5
[1498/1800] seed=47 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.853 deaths=2 segments=7
[1499/1800] seed=48 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.851 deaths=4 segments=9
[1500/1800] seed=49 decay=0.90 fill=1.60 p=0.55 smellR=14 | comfort=0.830 deaths=2 segments=7

--- checkpoint after 1500 runs | elapsed 56.2 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1501/1800] seed=00 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.865 deaths=3 segments=8
[1502/1800] seed=01 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.841 deaths=4 segments=9
[1503/1800] seed=02 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.870 deaths=5 segments=10
[1504/1800] seed=03 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.802 deaths=4 segments=9
[1505/1800] seed=04 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.818 deaths=5 segments=10
[1506/1800] seed=05 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.806 deaths=1 segments=6
[1507/1800] seed=06 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.859 deaths=0 segments=5
[1508/1800] seed=07 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.836 deaths=0 segments=5
[1509/1800] seed=08 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.835 deaths=2 segments=7
[1510/1800] seed=09 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=4 segments=9
[1511/1800] seed=10 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.838 deaths=3 segments=8
[1512/1800] seed=11 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.792 deaths=6 segments=11
[1513/1800] seed=12 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.836 deaths=0 segments=5
[1514/1800] seed=13 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.843 deaths=6 segments=11
[1515/1800] seed=14 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.836 deaths=3 segments=8
[1516/1800] seed=15 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.791 deaths=6 segments=11
[1517/1800] seed=16 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.804 deaths=4 segments=9
[1518/1800] seed=17 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.857 deaths=4 segments=9
[1519/1800] seed=18 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.869 deaths=1 segments=6
[1520/1800] seed=19 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.825 deaths=3 segments=8
[1521/1800] seed=20 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=1 segments=6
[1522/1800] seed=21 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.840 deaths=1 segments=6
[1523/1800] seed=22 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=4 segments=9
[1524/1800] seed=23 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.801 deaths=10 segments=15
[1525/1800] seed=24 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.796 deaths=3 segments=8

--- checkpoint after 1525 runs | elapsed 57.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1526/1800] seed=25 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.830 deaths=3 segments=8
[1527/1800] seed=26 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.802 deaths=7 segments=12
[1528/1800] seed=27 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.831 deaths=6 segments=11
[1529/1800] seed=28 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.781 deaths=5 segments=10
[1530/1800] seed=29 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.823 deaths=3 segments=8
[1531/1800] seed=30 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.817 deaths=6 segments=11
[1532/1800] seed=31 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.846 deaths=3 segments=8
[1533/1800] seed=32 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.797 deaths=4 segments=9
[1534/1800] seed=33 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.828 deaths=7 segments=12
[1535/1800] seed=34 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.864 deaths=2 segments=7
[1536/1800] seed=35 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.810 deaths=9 segments=14
[1537/1800] seed=36 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.833 deaths=5 segments=10
[1538/1800] seed=37 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.755 deaths=9 segments=14
[1539/1800] seed=38 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.820 deaths=3 segments=8
[1540/1800] seed=39 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.798 deaths=4 segments=9
[1541/1800] seed=40 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.832 deaths=2 segments=7
[1542/1800] seed=41 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.850 deaths=2 segments=7
[1543/1800] seed=42 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.809 deaths=5 segments=10
[1544/1800] seed=43 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.810 deaths=4 segments=9
[1545/1800] seed=44 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.812 deaths=4 segments=9
[1546/1800] seed=45 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.863 deaths=3 segments=8
[1547/1800] seed=46 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.835 deaths=0 segments=5
[1548/1800] seed=47 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=3 segments=8
[1549/1800] seed=48 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.777 deaths=8 segments=13
[1550/1800] seed=49 decay=0.90 fill=1.60 p=0.75 smellR=10 | comfort=0.821 deaths=7 segments=12

--- checkpoint after 1550 runs | elapsed 58.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1551/1800] seed=00 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.865 deaths=3 segments=8
[1552/1800] seed=01 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.863 deaths=1 segments=6
[1553/1800] seed=02 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.870 deaths=5 segments=10
[1554/1800] seed=03 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.779 deaths=5 segments=10
[1555/1800] seed=04 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.818 deaths=5 segments=10
[1556/1800] seed=05 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.806 deaths=1 segments=6
[1557/1800] seed=06 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.829 deaths=0 segments=5
[1558/1800] seed=07 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.836 deaths=0 segments=5
[1559/1800] seed=08 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=2 segments=7
[1560/1800] seed=09 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.850 deaths=1 segments=6
[1561/1800] seed=10 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.806 deaths=7 segments=12
[1562/1800] seed=11 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.792 deaths=6 segments=11
[1563/1800] seed=12 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.836 deaths=0 segments=5
[1564/1800] seed=13 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.843 deaths=6 segments=11
[1565/1800] seed=14 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.865 deaths=0 segments=5
[1566/1800] seed=15 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.779 deaths=8 segments=13
[1567/1800] seed=16 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.809 deaths=1 segments=6
[1568/1800] seed=17 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.853 deaths=4 segments=9
[1569/1800] seed=18 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.869 deaths=1 segments=6
[1570/1800] seed=19 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.856 deaths=2 segments=7
[1571/1800] seed=20 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=1 segments=6
[1572/1800] seed=21 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.823 deaths=2 segments=7
[1573/1800] seed=22 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.855 deaths=2 segments=7
[1574/1800] seed=23 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.847 deaths=2 segments=7
[1575/1800] seed=24 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.848 deaths=4 segments=9

--- checkpoint after 1575 runs | elapsed 59.1 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1576/1800] seed=25 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.839 deaths=4 segments=9
[1577/1800] seed=26 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.820 deaths=3 segments=8
[1578/1800] seed=27 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.831 deaths=6 segments=11
[1579/1800] seed=28 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.781 deaths=5 segments=10
[1580/1800] seed=29 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.803 deaths=5 segments=10
[1581/1800] seed=30 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.801 deaths=2 segments=7
[1582/1800] seed=31 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.846 deaths=3 segments=8
[1583/1800] seed=32 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.797 deaths=4 segments=9
[1584/1800] seed=33 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.828 deaths=7 segments=12
[1585/1800] seed=34 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.864 deaths=2 segments=7
[1586/1800] seed=35 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.810 deaths=9 segments=14
[1587/1800] seed=36 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.816 deaths=6 segments=11
[1588/1800] seed=37 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.851 deaths=1 segments=6
[1589/1800] seed=38 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.820 deaths=3 segments=8
[1590/1800] seed=39 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.798 deaths=4 segments=9
[1591/1800] seed=40 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.832 deaths=2 segments=7
[1592/1800] seed=41 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.850 deaths=2 segments=7
[1593/1800] seed=42 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.808 deaths=7 segments=12
[1594/1800] seed=43 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.844 deaths=4 segments=9
[1595/1800] seed=44 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=4 segments=9
[1596/1800] seed=45 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.863 deaths=3 segments=8
[1597/1800] seed=46 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.835 deaths=0 segments=5
[1598/1800] seed=47 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.804 deaths=5 segments=10
[1599/1800] seed=48 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.820 deaths=6 segments=11
[1600/1800] seed=49 decay=0.90 fill=1.60 p=0.75 smellR=14 | comfort=0.830 deaths=3 segments=8

--- checkpoint after 1600 runs | elapsed 60.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1601/1800] seed=00 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.746 deaths=1 segments=6
[1602/1800] seed=01 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.754 deaths=1 segments=6
[1603/1800] seed=02 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=1 segments=6
[1604/1800] seed=03 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=1 segments=6
[1605/1800] seed=04 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.719 deaths=6 segments=11
[1606/1800] seed=05 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.747 deaths=2 segments=7
[1607/1800] seed=06 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.742 deaths=7 segments=12
[1608/1800] seed=07 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.751 deaths=0 segments=5
[1609/1800] seed=08 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.738 deaths=4 segments=9
[1610/1800] seed=09 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.731 deaths=3 segments=8
[1611/1800] seed=10 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.753 deaths=1 segments=6
[1612/1800] seed=11 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.745 deaths=4 segments=9
[1613/1800] seed=12 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.720 deaths=6 segments=11
[1614/1800] seed=13 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.767 deaths=4 segments=9
[1615/1800] seed=14 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.749 deaths=0 segments=5
[1616/1800] seed=15 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.733 deaths=1 segments=6
[1617/1800] seed=16 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=2 segments=7
[1618/1800] seed=17 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.730 deaths=2 segments=7
[1619/1800] seed=18 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.790 deaths=1 segments=6
[1620/1800] seed=19 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.723 deaths=6 segments=11
[1621/1800] seed=20 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.730 deaths=7 segments=12
[1622/1800] seed=21 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.741 deaths=3 segments=8
[1623/1800] seed=22 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.745 deaths=0 segments=5
[1624/1800] seed=23 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=3 segments=8
[1625/1800] seed=24 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.721 deaths=7 segments=12

--- checkpoint after 1625 runs | elapsed 61.0 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1626/1800] seed=25 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.730 deaths=1 segments=6
[1627/1800] seed=26 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.742 deaths=4 segments=9
[1628/1800] seed=27 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.765 deaths=0 segments=5
[1629/1800] seed=28 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.782 deaths=2 segments=7
[1630/1800] seed=29 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.767 deaths=1 segments=6
[1631/1800] seed=30 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.771 deaths=2 segments=7
[1632/1800] seed=31 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=4 segments=9
[1633/1800] seed=32 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.750 deaths=3 segments=8
[1634/1800] seed=33 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.748 deaths=0 segments=5
[1635/1800] seed=34 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.770 deaths=2 segments=7
[1636/1800] seed=35 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.749 deaths=3 segments=8
[1637/1800] seed=36 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.741 deaths=0 segments=5
[1638/1800] seed=37 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.736 deaths=3 segments=8
[1639/1800] seed=38 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=1 segments=6
[1640/1800] seed=39 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.756 deaths=1 segments=6
[1641/1800] seed=40 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.747 deaths=4 segments=9
[1642/1800] seed=41 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.766 deaths=1 segments=6
[1643/1800] seed=42 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.757 deaths=4 segments=9
[1644/1800] seed=43 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.758 deaths=2 segments=7
[1645/1800] seed=44 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.745 deaths=0 segments=5
[1646/1800] seed=45 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.740 deaths=3 segments=8
[1647/1800] seed=46 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.755 deaths=0 segments=5
[1648/1800] seed=47 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.754 deaths=1 segments=6
[1649/1800] seed=48 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.769 deaths=0 segments=5
[1650/1800] seed=49 decay=0.90 fill=1.90 p=0.55 smellR=10 | comfort=0.743 deaths=4 segments=9

--- checkpoint after 1650 runs | elapsed 61.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1651/1800] seed=00 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.737 deaths=1 segments=6
[1652/1800] seed=01 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.763 deaths=5 segments=10
[1653/1800] seed=02 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.739 deaths=2 segments=7
[1654/1800] seed=03 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.738 deaths=1 segments=6
[1655/1800] seed=04 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.722 deaths=3 segments=8
[1656/1800] seed=05 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.747 deaths=2 segments=7
[1657/1800] seed=06 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=3 segments=8
[1658/1800] seed=07 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.756 deaths=2 segments=7
[1659/1800] seed=08 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.738 deaths=4 segments=9
[1660/1800] seed=09 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.748 deaths=1 segments=6
[1661/1800] seed=10 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.719 deaths=4 segments=9
[1662/1800] seed=11 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.745 deaths=4 segments=9
[1663/1800] seed=12 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.719 deaths=4 segments=9
[1664/1800] seed=13 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.772 deaths=4 segments=9
[1665/1800] seed=14 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.749 deaths=0 segments=5
[1666/1800] seed=15 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.720 deaths=6 segments=11
[1667/1800] seed=16 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=2 segments=7
[1668/1800] seed=17 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.745 deaths=3 segments=8
[1669/1800] seed=18 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.790 deaths=1 segments=6
[1670/1800] seed=19 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.742 deaths=1 segments=6
[1671/1800] seed=20 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.740 deaths=6 segments=11
[1672/1800] seed=21 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.723 deaths=3 segments=8
[1673/1800] seed=22 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.757 deaths=1 segments=6
[1674/1800] seed=23 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.711 deaths=6 segments=11
[1675/1800] seed=24 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.734 deaths=1 segments=6

--- checkpoint after 1675 runs | elapsed 62.9 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1676/1800] seed=25 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.730 deaths=1 segments=6
[1677/1800] seed=26 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.760 deaths=0 segments=5
[1678/1800] seed=27 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.758 deaths=2 segments=7
[1679/1800] seed=28 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.782 deaths=2 segments=7
[1680/1800] seed=29 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.767 deaths=1 segments=6
[1681/1800] seed=30 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.771 deaths=2 segments=7
[1682/1800] seed=31 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.751 deaths=3 segments=8
[1683/1800] seed=32 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.756 deaths=2 segments=7
[1684/1800] seed=33 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.748 deaths=0 segments=5
[1685/1800] seed=34 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.723 deaths=3 segments=8
[1686/1800] seed=35 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.749 deaths=3 segments=8
[1687/1800] seed=36 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.787 deaths=0 segments=5
[1688/1800] seed=37 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.736 deaths=3 segments=8
[1689/1800] seed=38 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=1 segments=6
[1690/1800] seed=39 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.722 deaths=8 segments=13
[1691/1800] seed=40 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.747 deaths=4 segments=9
[1692/1800] seed=41 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.766 deaths=1 segments=6
[1693/1800] seed=42 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.757 deaths=4 segments=9
[1694/1800] seed=43 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.758 deaths=2 segments=7
[1695/1800] seed=44 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.745 deaths=0 segments=5
[1696/1800] seed=45 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.740 deaths=3 segments=8
[1697/1800] seed=46 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=0 segments=5
[1698/1800] seed=47 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.756 deaths=2 segments=7
[1699/1800] seed=48 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.774 deaths=0 segments=5
[1700/1800] seed=49 decay=0.90 fill=1.90 p=0.55 smellR=14 | comfort=0.755 deaths=2 segments=7

--- checkpoint after 1700 runs | elapsed 63.8 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1701/1800] seed=00 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.741 deaths=6 segments=11
[1702/1800] seed=01 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.755 deaths=3 segments=8
[1703/1800] seed=02 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.769 deaths=4 segments=9
[1704/1800] seed=03 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.741 deaths=4 segments=9
[1705/1800] seed=04 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.738 deaths=5 segments=10
[1706/1800] seed=05 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.751 deaths=1 segments=6
[1707/1800] seed=06 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.781 deaths=0 segments=5
[1708/1800] seed=07 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.758 deaths=1 segments=6
[1709/1800] seed=08 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.758 deaths=2 segments=7
[1710/1800] seed=09 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.740 deaths=4 segments=9
[1711/1800] seed=10 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.732 deaths=4 segments=9
[1712/1800] seed=11 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.731 deaths=3 segments=8
[1713/1800] seed=12 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.735 deaths=0 segments=5
[1714/1800] seed=13 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.742 deaths=6 segments=11
[1715/1800] seed=14 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.728 deaths=3 segments=8
[1716/1800] seed=15 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.723 deaths=6 segments=11
[1717/1800] seed=16 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.746 deaths=3 segments=8
[1718/1800] seed=17 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.772 deaths=4 segments=9
[1719/1800] seed=18 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.779 deaths=1 segments=6
[1720/1800] seed=19 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.739 deaths=3 segments=8
[1721/1800] seed=20 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.737 deaths=5 segments=10
[1722/1800] seed=21 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.762 deaths=1 segments=6
[1723/1800] seed=22 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.757 deaths=3 segments=8
[1724/1800] seed=23 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.703 deaths=6 segments=11
[1725/1800] seed=24 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.760 deaths=3 segments=8

--- checkpoint after 1725 runs | elapsed 64.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1726/1800] seed=25 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.752 deaths=3 segments=8
[1727/1800] seed=26 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.726 deaths=4 segments=9
[1728/1800] seed=27 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.727 deaths=6 segments=11
[1729/1800] seed=28 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.754 deaths=1 segments=6
[1730/1800] seed=29 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.740 deaths=3 segments=8
[1731/1800] seed=30 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.729 deaths=5 segments=10
[1732/1800] seed=31 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.748 deaths=2 segments=7
[1733/1800] seed=32 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.724 deaths=4 segments=9
[1734/1800] seed=33 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.767 deaths=2 segments=7
[1735/1800] seed=34 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.754 deaths=2 segments=7
[1736/1800] seed=35 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.738 deaths=9 segments=14
[1737/1800] seed=36 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.736 deaths=3 segments=8
[1738/1800] seed=37 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.692 deaths=9 segments=14
[1739/1800] seed=38 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.748 deaths=3 segments=8
[1740/1800] seed=39 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.750 deaths=2 segments=7
[1741/1800] seed=40 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.724 deaths=3 segments=8
[1742/1800] seed=41 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.724 deaths=5 segments=10
[1743/1800] seed=42 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.739 deaths=5 segments=10
[1744/1800] seed=43 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.757 deaths=2 segments=7
[1745/1800] seed=44 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.722 deaths=3 segments=8
[1746/1800] seed=45 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.733 deaths=5 segments=10
[1747/1800] seed=46 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.749 deaths=0 segments=5
[1748/1800] seed=47 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.749 deaths=0 segments=5
[1749/1800] seed=48 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.708 deaths=8 segments=13
[1750/1800] seed=49 decay=0.90 fill=1.90 p=0.75 smellR=10 | comfort=0.765 deaths=5 segments=10

--- checkpoint after 1750 runs | elapsed 65.7 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1751/1800] seed=00 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.726 deaths=5 segments=10
[1752/1800] seed=01 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.721 deaths=6 segments=11
[1753/1800] seed=02 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.758 deaths=3 segments=8
[1754/1800] seed=03 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.729 deaths=3 segments=8
[1755/1800] seed=04 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.738 deaths=5 segments=10
[1756/1800] seed=05 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.751 deaths=1 segments=6
[1757/1800] seed=06 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.755 deaths=1 segments=6
[1758/1800] seed=07 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.758 deaths=1 segments=6
[1759/1800] seed=08 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.758 deaths=2 segments=7
[1760/1800] seed=09 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.740 deaths=1 segments=6
[1761/1800] seed=10 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=3 segments=8
[1762/1800] seed=11 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.731 deaths=3 segments=8
[1763/1800] seed=12 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.735 deaths=0 segments=5
[1764/1800] seed=13 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.742 deaths=6 segments=11
[1765/1800] seed=14 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.754 deaths=0 segments=5
[1766/1800] seed=15 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.745 deaths=1 segments=6
[1767/1800] seed=16 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.740 deaths=3 segments=8
[1768/1800] seed=17 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.772 deaths=4 segments=9
[1769/1800] seed=18 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.779 deaths=1 segments=6
[1770/1800] seed=19 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.761 deaths=2 segments=7
[1771/1800] seed=20 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.734 deaths=5 segments=10
[1772/1800] seed=21 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.739 deaths=3 segments=8
[1773/1800] seed=22 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.745 deaths=2 segments=7
[1774/1800] seed=23 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.767 deaths=2 segments=7
[1775/1800] seed=24 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.723 deaths=2 segments=7

--- checkpoint after 1775 runs | elapsed 66.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

[1776/1800] seed=25 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=4 segments=9
[1777/1800] seed=26 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.725 deaths=5 segments=10
[1778/1800] seed=27 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.727 deaths=6 segments=11
[1779/1800] seed=28 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.754 deaths=1 segments=6
[1780/1800] seed=29 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.736 deaths=3 segments=8
[1781/1800] seed=30 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.735 deaths=2 segments=7
[1782/1800] seed=31 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.748 deaths=2 segments=7
[1783/1800] seed=32 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.724 deaths=4 segments=9
[1784/1800] seed=33 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.767 deaths=2 segments=7
[1785/1800] seed=34 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.754 deaths=2 segments=7
[1786/1800] seed=35 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.738 deaths=9 segments=14
[1787/1800] seed=36 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.743 deaths=11 segments=16
[1788/1800] seed=37 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.774 deaths=1 segments=6
[1789/1800] seed=38 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.748 deaths=3 segments=8
[1790/1800] seed=39 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.762 deaths=2 segments=7
[1791/1800] seed=40 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.724 deaths=3 segments=8
[1792/1800] seed=41 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.724 deaths=5 segments=10
[1793/1800] seed=42 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.723 deaths=7 segments=12
[1794/1800] seed=43 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.757 deaths=2 segments=7
[1795/1800] seed=44 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.722 deaths=3 segments=8
[1796/1800] seed=45 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.737 deaths=3 segments=8
[1797/1800] seed=46 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=0 segments=5
[1798/1800] seed=47 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.749 deaths=0 segments=5
[1799/1800] seed=48 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.740 deaths=6 segments=11
[1800/1800] seed=49 decay=0.90 fill=1.90 p=0.75 smellR=14 | comfort=0.765 deaths=5 segments=10

--- checkpoint after 1800 runs | elapsed 67.6 min ---

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50

DONE
raw saved to: sweep_outputs\oracle_smell_decay_fill_coarse_50seed_raw.csv
summary saved to: sweep_outputs\oracle_smell_decay_fill_coarse_50seed_summary.csv

,decay_mult,fill_target,persist_p,smell_radius,mean_comfort_mean,mean_comfort_std,eval_deaths_mean,eval_deaths_median,eval_deaths_max,zero_death_seeds,eval_segments_mean,eval_segments_max,eval_timeouts_mean,water_ticks_mean,food_ticks_mean,explorer_calls_mean,smell_follow_mean,smell_reverse_mean,momentum_persist_mean,n
0,0.7,1.3,0.55,10,0.895330,0.024623,1.54,1.0,5,13,6.54,10,4.0,1119.32,438.28,757.84,203.52,52.76,124.52,50
1,0.7,1.3,0.55,14,0.887743,0.027077,1.56,1.5,6,14,6.56,11,4.0,1106.70,429.68,748.12,204.70,53.58,121.12,50
5,0.7,1.6,0.55,14,0.819504,0.029533,1.60,1.0,6,11,6.60,11,4.0,1035.94,420.30,761.72,204.66,54.14,125.34,50
8,0.7,1.9,0.55,10,0.737915,0.019273,1.70,1.0,7,12,6.70,12,4.0,1003.46,465.64,777.12,205.10,53.26,129.08,50
9,0.7,1.9,0.55,14,0.735902,0.021629,1.84,1.0,7,12,6.84,12,4.0,1004.34,466.06,764.58,205.72,54.74,125.88,50
4,0.7,1.6,0.55,10,0.820967,0.029753,1.90,2.0,6,10,6.90,11,4.0,1045.92,422.04,782.20,207.20,55.28,130.22,50
21,0.8,1.9,0.55,14,0.741932,0.016661,2.08,2.0,8,7,7.08,13,4.0,1038.70,489.32,738.50,201.22,52.88,117.96,50
20,0.8,1.9,0.55,10,0.740854,0.019170,2.10,2.0,6,8,7.10,11,4.0,1037.30,494.60,765.04,200.78,53.38,125.74,50
13,0.8,1.3,0.55,14,0.896755,0.023178,2.14,2.0,6,7,7.14,11,4.0,1155.24,463.72,742.90,209.38,54.36,116.24,50
17,0.8,1.6,0.55,14,0.831089,0.020934,2.16,2.0,6,8,7.16,11,4.0,1110.80,444.98,732.24,203.00,53.68,115.84,50
28,0.9,1.6,0.55,10,0.837278,0.021229,2.34,2.0,6,5,7.34,11,4.0,1146.24,462.76,772.54,207.52,56.06,124.28,50
32,0.9,1.9,0.55,10,0.747831,0.015234,2.38,2.0,7,9,7.38,12,4.0,1065.74,507.90,780.68,204.80,55.12,128.40,50
33,0.9,1.9,0.55,14,0.748217,0.017891,2.38,2.0,8,7,7.38,13,4.0,1065.04,510.24,786.08,211.44,57.28,127.90,50
12,0.8,1.3,0.55,10,0.893823,0.024301,2.38,2.0,8,7,7.38,13,4.0,1157.72,459.34,772.10,209.28,54.82,123.90,50
29,0.9,1.6,0.55,14,0.834547,0.023729,2.40,2.0,6,4,7.40,11,4.0,1149.80,460.92,790.10,213.94,58.56,127.90,50
16,0.8,1.6,0.55,10,0.828682,0.027393,2.40,2.0,8,6,7.40,13,4.0,1106.88,445.96,757.84,204.62,53.94,122.10,50
25,0.9,1.3,0.55,14,0.897044,0.017073,2.42,2.0,7,3,7.42,12,4.0,1223.44,480.20,764.60,212.60,55.52,121.34,50
11,0.7,1.9,0.75,14,0.725993,0.019485,2.58,3.0,8,6,7.58,13,4.0,988.38,451.86,1168.08,249.38,84.34,294.28,50
24,0.9,1.3,0.55,10,0.892818,0.017221,2.62,2.0,7,6,7.62,12,4.0,1194.52,476.88,788.32,210.04,55.24,128.54,50
10,0.7,1.9,0.75,10,0.728947,0.019198,2.64,3.0,7,6,7.64,12,4.0,964.14,462.66,1182.26,247.38,84.60,299.56,50
3,0.7,1.3,0.75,14,0.882439,0.026184,2.70,3.0,7,6,7.70,12,4.0,1089.52,426.16,1167.72,252.90,83.14,291.76,50
2,0.7,1.3,0.75,10,0.880464,0.029309,2.74,3.0,10,7,7.74,15,4.0,1074.28,430.04,1181.14,249.48,82.58,298.82,50
15,0.8,1.3,0.75,14,0.890314,0.024101,2.90,2.5,11,4,7.90,16,4.0,1148.78,453.50,1166.82,252.16,84.02,291.74,50
23,0.8,1.9,0.75,14,0.729335,0.020159,2.96,2.0,11,4,7.96,16,4.0,1007.78,468.34,1158.10,255.36,85.42,285.68,50
6,0.7,1.6,0.75,10,0.813104,0.028426,3.00,3.0,10,6,8.00,15,4.0,1037.52,415.50,1154.16,244.26,80.78,292.58,50
18,0.8,1.6,0.75,10,0.817883,0.029011,3.00,2.0,12,3,8.00,17,4.0,1078.96,428.98,1207.86,256.30,85.72,303.82,50
7,0.7,1.6,0.75,14,0.813305,0.024399,3.06,3.0,9,4,8.06,14,4.0,1035.84,419.22,1145.20,248.92,82.56,286.54,50
22,0.8,1.9,0.75,10,0.729542,0.022863,3.06,3.0,10,4,8.06,15,4.0,1012.36,460.56,1207.26,255.20,86.02,303.80,50
19,0.8,1.6,0.75,14,0.818117,0.027949,3.08,3.0,12,4,8.08,17,4.0,1061.42,434.62,1180.06,255.78,85.44,294.22,50
35,0.9,1.9,0.75,14,0.744135,0.015370,3.12,3.0,11,4,8.12,16,4.0,1059.78,487.58,1129.94,251.56,82.14,276.02,50

In [6]:
%reload_ext autoreload
%autoreload 2

import numpy as np
import world_v1 as world


def starvation_time_water_perfect(
    seed=0,
    radius=20,
    decay_mult=0.2,
    h_fixed=1.60,
    s0=1.60,
    max_ticks=20_000,
    day_len=50,
):
    """
    Best-case starvation clock:
        hydration is clamped to h_fixed every tick
        no food is eaten
        satiation decays using your real world_v1 function
    """
    np.random.seed(seed)

    h_scale, s_scale = world.decay_scaling(radius)
    h_scale *= decay_mult
    s_scale *= decay_mult

    s = float(s0)

    for t in range(max_ticks):
        b = world.brightness(t, day_len=day_len, noise=True)

        # perfect water management assumption
        h = float(h_fixed)

        s = world.decay_satiation(s, h, b, s_scale)
        s = float(np.clip(s, 0.0, world.SMAX))

        if s <= world.DEATH_THRESH:
            return t + 1

    return max_ticks


for decay_mult in [1.0, 0.7, 0.5, 0.3, 0.25, 0.2]:
    times = [
        starvation_time_water_perfect(
            seed=seed,
            decay_mult=decay_mult,
            h_fixed=1.60,
            s0=1.60,
        )
        for seed in range(100)
    ]

    print(
        f"decay_mult={decay_mult:.2f} | "
        f"mean={np.mean(times):.1f} | "
        f"median={np.median(times):.1f} | "
        f"min={np.min(times)} | "
        f"max={np.max(times)}"
    )

decay_mult=1.00 | mean=635.1 | median=635.5 | min=608 | max=666
decay_mult=0.70 | mean=906.8 | median=907.5 | min=872 | max=942
decay_mult=0.50 | mean=1268.5 | median=1268.0 | min=1217 | max=1317
decay_mult=0.30 | mean=2113.7 | median=2112.0 | min=2053 | max=2197
decay_mult=0.25 | mean=2536.8 | median=2535.0 | min=2475 | max=2633
decay_mult=0.20 | mean=3169.9 | median=3170.0 | min=3096 | max=3278

In [1]:
import importlib
import inspect

mod = importlib.import_module("model_modules.oracle_modules.consumer_oracle_v1")

print("file:", mod.__file__)
print("\nNames containing Oracle / Consumer / Eat / Drink:")
for name in dir(mod):
    if any(s in name.lower() for s in ["oracle", "consumer", "eat", "drink"]):
        obj = getattr(mod, name)
        print(" ", name, type(obj))

file: c:\Users\Adarsh Arun\Downloads\homeostatic-agents-main\prototypes\06_feudal\model_modules\oracle_modules\consumer_oracle_v1.py

Names containing Oracle / Consumer / Eat / Drink:
  Consumer <class 'abc.ABCMeta'>
  ConsumerObs <class 'type'>
  OracleConsumer <class 'abc.ABCMeta'>
  make_drink <class 'function'>
  make_eat <class 'function'>

In [1]:
from sweep_fn_v5 import load_and_report

PROTOTYPE_NAME = "05_generalisation"
EXPERIMENT_NAME = PROTOTYPE_NAME + "__" + "self_imitation_v1"

res, manifest, runs_df, summary_df = load_and_report(EXPERIMENT_NAME, PROTOTYPE_NAME)

loaded experiment: 05_generalisation__self_imitation_v1
configs: 3   runs: 72

,config,solved,95% wilson,clean,comfort_med,deaths_med,zero_death,food%,water%
0,sil_frac_0,0% (0/24),[0%–14%],4%,0.55,145.5,0%,2.1,44.5
1,sil_frac_0p25,0% (0/24),[0%–14%],4%,0.55,124.5,0%,1.4,59.2
2,sil_frac_0p5,0% (0/24),[0%–14%],4%,0.46,162.0,0%,2.2,43.8

config reports:

==========================================================================================
CONFIG: sil_frac_0
==========================================================================================
Solved rate: 0.0% (0/24 seeds), 95% Wilson [0.0%, 13.8%].
Clean-solve (crossed the valley, no death cap): 4.2% (1/24) — the gap to solved is the survival cost of the crossing.
Comfort: median 0.555, mean 0.550, std 0.052, range 0.423 to 0.634.
Deaths: median 145.5, mean 147.9, range 105 to 188, zero-death rate 0.0%.
Resource occupancy: food 2.07%, water 44.49%, water:food ratio 2.09.
Camp shape: water-camp score 0.46, dominant-cell occupancy 3.54%.
Water→food route: success rate 0.001, success count median 2.0, path efficiency 0.611, perfect-ish trip rate 0.000.
Food→water route: success rate 0.057, success count median 3.0, path efficiency 0.679.
Two-way route floor: 0.001; total successful resource trips median 5.0.
Bug check: max non-neighbour jumps = 3.

==========================================================================================
CONFIG: sil_frac_0p25
==========================================================================================
Solved rate: 0.0% (0/24 seeds), 95% Wilson [0.0%, 13.8%].
Clean-solve (crossed the valley, no death cap): 4.2% (1/24) — the gap to solved is the survival cost of the crossing.
Comfort: median 0.547, mean 0.543, std 0.062, range 0.440 to 0.670.
Deaths: median 124.5, mean 124.4, range 76 to 179, zero-death rate 0.0%.
Resource occupancy: food 1.43%, water 59.17%, water:food ratio 3.10.
Camp shape: water-camp score 0.67, dominant-cell occupancy 4.76%.
Water→food route: success rate 0.040, success count median 5.0, path efficiency 0.550, perfect-ish trip rate 0.000.
Food→water route: success rate 0.139, success count median 5.0, path efficiency 0.468.
Two-way route floor: 0.029; total successful resource trips median 10.0.
Bug check: max non-neighbour jumps = 6.

==========================================================================================
CONFIG: sil_frac_0p5
==========================================================================================
Solved rate: 0.0% (0/24 seeds), 95% Wilson [0.0%, 13.8%].
Clean-solve (crossed the valley, no death cap): 4.2% (1/24) — the gap to solved is the survival cost of the crossing.
Comfort: median 0.459, mean 0.458, std 0.040, range 0.380 to 0.529.
Deaths: median 162.0, mean 164.3, range 102 to 247, zero-death rate 0.0%.
Resource occupancy: food 2.17%, water 43.80%, water:food ratio 1.20.
Camp shape: water-camp score 0.07, dominant-cell occupancy 4.60%.
Water→food route: success rate 0.055, success count median 6.5, path efficiency 0.463, perfect-ish trip rate 0.155.
Food→water route: success rate 0.108, success count median 4.0, path efficiency 0.547.
Two-way route floor: 0.049; total successful resource trips median 12.0.
Bug check: max non-neighbour jumps = 5.

saved summary CSVs to: c:\Users\Adarsh Arun\Downloads\homeostatic-agents-main\prototypes\05_generalisation\results\sweeps\05_generalisation__self_imitation_v1